{
  "acts": [
    "ACT.UNDERDOCKS",
    "ACT.HIVE",
    "ACT.GLORY"
  ],
  "ascension": 7,
  "build_id": "v0.98.2",
  "game_mode": "standard",
  "killed_by_encounter": "NONE.NONE",
  "killed_by_event": "NONE.NONE",
  "map_point_history": [
    [
      {
        "map_point_type": "ancient",
        "player_stats": [
          {
            "ancient_choice": [
              {
                "TextKey": "NEOWS_TORMENT",
                "title": {
                  "key": "NEOWS_TORMENT.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "STONE_HUMIDIFIER",
                "title": {
                  "key": "STONE_HUMIDIFIER.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "LEAFY_POULTICE",
                "title": {
                  "key": "LEAFY_POULTICE.title",
                  "table": "relics"
                },
                "was_chosen": true
              }
            ],
            "cards_transformed": [
              {
                "final_card": {
                  "floor_added_to_deck": 1,
                  "id": "CARD.SOW"
                },
                "original_card": {
                  "floor_added_to_deck": 1,
                  "id": "CARD.STRIKE_NECROBINDER"
                }
              },
              {
                "final_card": {
                  "floor_added_to_deck": 1,
                  "id": "CARD.LEGION_OF_BONE"
                },
                "original_card": {
                  "floor_added_to_deck": 1,
                  "id": "CARD.DEFEND_NECROBINDER"
                }
              }
            ],
            "current_gold": 99,
            "current_hp": 52,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "LEAFY_POULTICE.title",
                  "table": "relics"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 52,
            "max_hp": 56,
            "max_hp_gained": 0,
            "max_hp_lost": 10,
            "player_id": 76561198005465391,
            "relic_choices": [
              {
                "choice": "RELIC.LEAFY_POULTICE",
                "was_picked": true
              }
            ]
          },
          {
            "ancient_choice": [
              {
                "TextKey": "MASSIVE_SCROLL",
                "title": {
                  "key": "MASSIVE_SCROLL.title",
                  "table": "relics"
                },
                "was_chosen": true
              },
              {
                "TextKey": "POMANDER",
                "title": {
                  "key": "POMANDER.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "CURSED_PEARL",
                "title": {
                  "key": "CURSED_PEARL.title",
                  "table": "relics"
                },
                "was_chosen": false
              }
            ],
            "card_choices": [
              {
                "card": {
                  "id": "CARD.LIFT"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.HUDDLE_UP"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.BELIEVE_IN_YOU"
              }
            ],
            "current_gold": 99,
            "current_hp": 60,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "MASSIVE_SCROLL.title",
                  "table": "relics"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 60,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561197999477537,
            "relic_choices": [
              {
                "choice": "RELIC.MASSIVE_SCROLL",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.NEOW",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 2,
                  "id": "CARD.REAVE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.DEATHS_DOOR"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.DEFY"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 2,
                "id": "CARD.REAVE"
              }
            ],
            "current_gold": 111,
            "current_hp": 52,
            "damage_taken": 0,
            "gold_gained": 12,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 56,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198005465391
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 2,
                  "id": "CARD.ASTRAL_PULSE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.GLOW"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.REFINE_BLADE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.ASTRAL_PULSE"
              }
            ],
            "current_gold": 111,
            "current_hp": 60,
            "damage_taken": 0,
            "gold_gained": 12,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561197999477537
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.SLUDGE_SPINNER_WEAK",
            "monster_ids": [
              "MONSTER.SLUDGE_SPINNER"
            ],
            "room_type": "monster",
            "turns_taken": 3
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "current_gold": 111,
            "current_hp": 38,
            "damage_taken": 14,
            "event_choices": [
              {
                "title": {
                  "key": "ROOM_FULL_OF_CHEESE.pages.INITIAL.options.SEARCH.title",
                  "table": "events"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 56,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198005465391,
            "relic_choices": [
              {
                "choice": "RELIC.CHOSEN_CHEESE",
                "was_picked": true
              }
            ]
          },
          {
            "current_gold": 111,
            "current_hp": 46,
            "damage_taken": 14,
            "event_choices": [
              {
                "title": {
                  "key": "ROOM_FULL_OF_CHEESE.pages.INITIAL.options.SEARCH.title",
                  "table": "events"
                },
                "variables": {}
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561197999477537,
            "relic_choices": [
              {
                "choice": "RELIC.CHOSEN_CHEESE",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.ROOM_FULL_OF_CHEESE",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 4,
                  "id": "CARD.VEILPIERCER"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.COUNTDOWN"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.DEFY"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 4,
                "id": "CARD.VEILPIERCER"
              }
            ],
            "current_gold": 118,
            "current_hp": 39,
            "damage_taken": 0,
            "gold_gained": 7,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 1,
            "max_hp": 57,
            "max_hp_gained": 1,
            "max_hp_lost": 0,
            "player_id": 76561198005465391
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 4,
                  "id": "CARD.PHOTON_CUT"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.CLOAK_OF_STARS"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.MANIFEST_AUTHORITY"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.PHOTON_CUT"
              }
            ],
            "current_gold": 124,
            "current_hp": 44,
            "damage_taken": 3,
            "gold_gained": 13,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 1,
            "max_hp": 76,
            "max_hp_gained": 1,
            "max_hp_lost": 0,
            "player_id": 76561197999477537
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.SEAPUNK_WEAK",
            "monster_ids": [
              "MONSTER.SEAPUNK"
            ],
            "room_type": "monster",
            "turns_taken": 3
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 5,
                  "id": "CARD.CLEANSE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.REAP"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.BONE_SHARDS"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 5,
                "id": "CARD.CLEANSE"
              }
            ],
            "current_gold": 127,
            "current_hp": 40,
            "damage_taken": 0,
            "gold_gained": 9,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 1,
            "max_hp": 58,
            "max_hp_gained": 1,
            "max_hp_lost": 0,
            "player_id": 76561198005465391,
            "potion_choices": [
              {
                "choice": "POTION.SPEED_POTION",
                "was_picked": true
              }
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 5,
                  "id": "CARD.CHILD_OF_THE_STARS"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.ASTRAL_PULSE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.COSMIC_INDIFFERENCE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.CHILD_OF_THE_STARS"
              }
            ],
            "current_gold": 135,
            "current_hp": 45,
            "damage_taken": 0,
            "gold_gained": 11,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 1,
            "max_hp": 77,
            "max_hp_gained": 1,
            "max_hp_lost": 0,
            "player_id": 76561197999477537
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.CORPSE_SLUGS_WEAK",
            "monster_ids": [
              "MONSTER.CORPSE_SLUG",
              "MONSTER.CORPSE_SLUG"
            ],
            "room_type": "monster",
            "turns_taken": 3
          }
        ]
      },
      {
        "map_point_type": "shop",
        "player_stats": [
          {
            "cards_removed": [
              {
                "floor_added_to_deck": 1,
                "id": "CARD.STRIKE_NECROBINDER"
              }
            ],
            "current_gold": 3,
            "current_hp": 40,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 49,
            "gold_spent": 75,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 58,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198005465391,
            "potion_choices": [
              {
                "choice": "POTION.ATTACK_POTION",
                "was_picked": true
              }
            ]
          },
          {
            "bought_potions": [
              "POTION.FIRE_POTION",
              "POTION.ATTACK_POTION"
            ],
            "card_choices": [
              {
                "card": {
                  "id": "CARD.ASTRAL_PULSE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.HEIRLOOM_HAMMER"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.COSMIC_INDIFFERENCE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.REFINE_BLADE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.PALE_BLUE_DOT"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.GANG_UP"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.THE_GAMBIT"
                },
                "was_picked": false
              }
            ],
            "current_gold": 37,
            "current_hp": 45,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 98,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 77,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561197999477537,
            "potion_choices": [
              {
                "choice": "POTION.FIRE_POTION",
                "was_picked": true
              },
              {
                "choice": "POTION.ATTACK_POTION",
                "was_picked": true
              },
              {
                "choice": "POTION.ENERGY_POTION",
                "was_picked": false
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.HAPPY_FLOWER",
                "was_picked": false
              },
              {
                "choice": "RELIC.GALACTIC_DUST",
                "was_picked": false
              },
              {
                "choice": "RELIC.LAVA_LAMP",
                "was_picked": false
              }
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "shop",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "elite",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "floor_added_to_deck": 7,
                  "id": "CARD.HAUNT"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.EIDOLON"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.POKE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "current_upgrade_level": 1,
                "floor_added_to_deck": 7,
                "id": "CARD.HAUNT"
              }
            ],
            "current_gold": 33,
            "current_hp": 29,
            "damage_taken": 12,
            "gold_gained": 30,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 1,
            "max_hp": 59,
            "max_hp_gained": 1,
            "max_hp_lost": 0,
            "player_id": 76561198005465391,
            "potion_choices": [
              {
                "choice": "POTION.SKILL_POTION",
                "was_picked": true
              }
            ],
            "potion_used": [
              "POTION.ATTACK_POTION"
            ],
            "relic_choices": [
              {
                "choice": "RELIC.FROZEN_EGG",
                "was_picked": true
              }
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 7,
                  "id": "CARD.REFLECT"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.ORBIT"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.QUASAR"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.REFLECT"
              }
            ],
            "current_gold": 68,
            "current_hp": 24,
            "damage_taken": 22,
            "gold_gained": 31,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 1,
            "max_hp": 78,
            "max_hp_gained": 1,
            "max_hp_lost": 0,
            "player_id": 76561197999477537,
            "potion_choices": [
              {
                "choice": "POTION.DUPLICATOR",
                "was_picked": true
              }
            ],
            "potion_used": [
              "POTION.ATTACK_POTION"
            ],
            "relic_choices": [
              {
                "choice": "RELIC.MEAL_TICKET",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.PHANTASMAL_GARDENERS_ELITE",
            "monster_ids": [
              "MONSTER.PHANTASMAL_GARDENER",
              "MONSTER.PHANTASMAL_GARDENER",
              "MONSTER.PHANTASMAL_GARDENER",
              "MONSTER.PHANTASMAL_GARDENER"
            ],
            "room_type": "elite",
            "turns_taken": 4
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 33,
            "current_hp": 46,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 17,
            "max_hp": 59,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198005465391,
            "rest_site_choices": [
              "HEAL"
            ]
          },
          {
            "current_gold": 68,
            "current_hp": 47,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 23,
            "max_hp": 78,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561197999477537,
            "rest_site_choices": [
              "HEAL"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "treasure",
        "player_stats": [
          {
            "current_gold": 66,
            "current_hp": 46,
            "damage_taken": 0,
            "gold_gained": 33,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 59,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198005465391,
            "relic_choices": [
              {
                "choice": "RELIC.PERMAFROST",
                "was_picked": true
              }
            ]
          },
          {
            "current_gold": 99,
            "current_hp": 47,
            "damage_taken": 0,
            "gold_gained": 31,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 78,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561197999477537,
            "relic_choices": [
              {
                "choice": "RELIC.AMETHYST_AUBERGINE",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "treasure",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "elite",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 10,
                  "id": "CARD.DEFILE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.REAVE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.NO_ESCAPE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 10,
                "id": "CARD.DEFILE"
              }
            ],
            "current_gold": 98,
            "current_hp": 42,
            "damage_taken": 5,
            "gold_gained": 32,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 1,
            "max_hp": 60,
            "max_hp_gained": 1,
            "max_hp_lost": 0,
            "player_id": 76561198005465391,
            "potion_choices": [
              {
                "choice": "POTION.ATTACK_POTION",
                "was_picked": true
              }
            ],
            "potion_used": [
              "POTION.SKILL_POTION"
            ],
            "relic_choices": [
              {
                "choice": "RELIC.HAPPY_FLOWER",
                "was_picked": true
              }
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 10,
                  "id": "CARD.ALIGNMENT"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.COSMIC_INDIFFERENCE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.DEVASTATE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.ALIGNMENT"
              }
            ],
            "current_gold": 140,
            "current_hp": 33,
            "damage_taken": 15,
            "gold_gained": 41,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 1,
            "max_hp": 79,
            "max_hp_gained": 1,
            "max_hp_lost": 0,
            "player_id": 76561197999477537,
            "potion_choices": [
              {
                "choice": "POTION.BLOCK_POTION",
                "was_picked": true
              }
            ],
            "potion_used": [
              "POTION.FIRE_POTION"
            ],
            "relic_choices": [
              {
                "choice": "RELIC.FENCING_MANUAL",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.SKULKING_COLONY_ELITE",
            "monster_ids": [
              "MONSTER.SKULKING_COLONY"
            ],
            "room_type": "elite",
            "turns_taken": 8
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "current_gold": 98,
            "current_hp": 34,
            "damage_taken": 8,
            "event_choices": [
              {
                "title": {
                  "key": "TRASH_HEAP.pages.INITIAL.options.DIVE_IN.title",
                  "table": "events"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 60,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198005465391,
            "relic_choices": [
              {
                "choice": "RELIC.DARKSTONE_PERIAPT",
                "was_picked": true
              }
            ]
          },
          {
            "current_gold": 140,
            "current_hp": 25,
            "damage_taken": 8,
            "event_choices": [
              {
                "title": {
                  "key": "TRASH_HEAP.pages.INITIAL.options.DIVE_IN.title",
                  "table": "events"
                },
                "variables": {}
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 79,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561197999477537,
            "relic_choices": [
              {
                "choice": "RELIC.HAND_DRILL",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.TRASH_HEAP",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 98,
            "current_hp": 52,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 18,
            "max_hp": 60,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198005465391,
            "rest_site_choices": [
              "HEAL"
            ]
          },
          {
            "current_gold": 140,
            "current_hp": 48,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 23,
            "max_hp": 79,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561197999477537,
            "rest_site_choices": [
              "HEAL"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "cards_gained": [
              {
                "id": "CARD.SPOILS_MAP",
                "props": {
                  "ints": [
                    {
                      "name": "SpoilsActIndex",
                      "value": 1
                    }
                  ]
                }
              }
            ],
            "current_gold": 98,
            "current_hp": 52,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "THE_LEGENDS_WERE_TRUE.pages.INITIAL.options.NAB_THE_MAP.title",
                  "table": "events"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 60,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198005465391
          },
          {
            "cards_gained": [
              {
                "id": "CARD.SPOILS_MAP",
                "props": {
                  "ints": [
                    {
                      "name": "SpoilsActIndex",
                      "value": 1
                    }
                  ]
                }
              }
            ],
            "current_gold": 140,
            "current_hp": 48,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "THE_LEGENDS_WERE_TRUE.pages.INITIAL.options.NAB_THE_MAP.title",
                  "table": "events"
                },
                "variables": {}
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 79,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561197999477537
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.THE_LEGENDS_WERE_TRUE",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "elite",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 14,
                  "id": "CARD.SEVERANCE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.SHROUD"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.REAVE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 14,
                "id": "CARD.SEVERANCE"
              }
            ],
            "current_gold": 129,
            "current_hp": 36,
            "damage_taken": 17,
            "gold_gained": 31,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 1,
            "max_hp": 61,
            "max_hp_gained": 1,
            "max_hp_lost": 0,
            "player_id": 76561198005465391,
            "potion_choices": [
              {
                "choice": "POTION.COLORLESS_POTION",
                "was_picked": true
              }
            ],
            "potion_used": [
              "POTION.ATTACK_POTION"
            ],
            "relic_choices": [
              {
                "choice": "RELIC.ANCHOR",
                "was_picked": true
              }
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 14,
                  "id": "CARD.WROUGHT_IN_WAR"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.CHILD_OF_THE_STARS"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.REFLECT"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.WROUGHT_IN_WAR"
              }
            ],
            "current_gold": 178,
            "current_hp": 31,
            "damage_taken": 18,
            "gold_gained": 38,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 1,
            "max_hp": 80,
            "max_hp_gained": 1,
            "max_hp_lost": 0,
            "player_id": 76561197999477537,
            "potion_choices": [
              {
                "choice": "POTION.POWER_POTION",
                "was_picked": true
              }
            ],
            "potion_used": [
              "POTION.BLOCK_POTION"
            ],
            "relic_choices": [
              {
                "choice": "RELIC.BRONZE_SCALES",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.TERROR_EEL_ELITE",
            "monster_ids": [
              "MONSTER.TERROR_EEL"
            ],
            "room_type": "elite",
            "turns_taken": 7
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 129,
            "current_hp": 36,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 61,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198005465391,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.REAVE"
            ]
          },
          {
            "current_gold": 178,
            "current_hp": 31,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561197999477537,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.VENERATE"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "boss",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "floor_added_to_deck": 16,
                  "id": "CARD.CALL_OF_THE_VOID"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.TIMES_UP"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.ERADICATE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "current_upgrade_level": 1,
                "floor_added_to_deck": 16,
                "id": "CARD.CALL_OF_THE_VOID"
              }
            ],
            "current_gold": 204,
            "current_hp": 22,
            "damage_taken": 15,
            "gold_gained": 75,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 1,
            "max_hp": 62,
            "max_hp_gained": 1,
            "max_hp_lost": 0,
            "player_id": 76561198005465391,
            "potion_choices": [
              {
                "choice": "POTION.STRENGTH_POTION",
                "was_picked": true
              }
            ],
            "potion_used": [
              "POTION.COLORLESS_POTION"
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 16,
                  "id": "CARD.VOID_FORM"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.DECISIONS_DECISIONS"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.SWORD_SAGE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.VOID_FORM"
              }
            ],
            "current_gold": 263,
            "current_hp": 14,
            "damage_taken": 18,
            "gold_gained": 85,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 1,
            "max_hp": 81,
            "max_hp_gained": 1,
            "max_hp_lost": 0,
            "player_id": 76561197999477537,
            "potion_used": [
              "POTION.POWER_POTION"
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.SOUL_FYSH_BOSS",
            "monster_ids": [
              "MONSTER.SOUL_FYSH"
            ],
            "room_type": "boss",
            "turns_taken": 8
          }
        ]
      }
    ],
    [
      {
        "map_point_type": "ancient",
        "player_stats": [
          {
            "ancient_choice": [
              {
                "TextKey": "PAELS_FLESH",
                "title": {
                  "key": "PAELS_FLESH.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "PAELS_CLAW",
                "title": {
                  "key": "PAELS_CLAW.title",
                  "table": "relics"
                },
                "was_chosen": true
              },
              {
                "TextKey": "PAELS_LEGION",
                "title": {
                  "key": "PAELS_LEGION.title",
                  "table": "relics"
                },
                "was_chosen": false
              }
            ],
            "cards_enchanted": [
              {
                "card": {
                  "enchantment": {
                    "amount": 1,
                    "id": "ENCHANTMENT.GOOPY"
                  },
                  "floor_added_to_deck": 1,
                  "id": "CARD.DEFEND_NECROBINDER"
                },
                "enchantment": "ENCHANTMENT.GOOPY"
              },
              {
                "card": {
                  "enchantment": {
                    "amount": 1,
                    "id": "ENCHANTMENT.GOOPY"
                  },
                  "floor_added_to_deck": 1,
                  "id": "CARD.DEFEND_NECROBINDER"
                },
                "enchantment": "ENCHANTMENT.GOOPY"
              },
              {
                "card": {
                  "enchantment": {
                    "amount": 1,
                    "id": "ENCHANTMENT.GOOPY"
                  },
                  "floor_added_to_deck": 1,
                  "id": "CARD.DEFEND_NECROBINDER"
                },
                "enchantment": "ENCHANTMENT.GOOPY"
              }
            ],
            "current_gold": 204,
            "current_hp": 54,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "PAELS_CLAW.title",
                  "table": "relics"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 32,
            "max_hp": 62,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198005465391,
            "relic_choices": [
              {
                "choice": "RELIC.PAELS_CLAW",
                "was_picked": true
              }
            ]
          },
          {
            "ancient_choice": [
              {
                "TextKey": "PAELS_HORN",
                "title": {
                  "key": "PAELS_HORN.title",
                  "table": "relics"
                },
                "was_chosen": true
              },
              {
                "TextKey": "PAELS_WING",
                "title": {
                  "key": "PAELS_WING.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "PAELS_LEGION",
                "title": {
                  "key": "PAELS_LEGION.title",
                  "table": "relics"
                },
                "was_chosen": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.RELAX"
              },
              {
                "id": "CARD.RELAX"
              }
            ],
            "current_gold": 263,
            "current_hp": 67,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "PAELS_HORN.title",
                  "table": "relics"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 53,
            "max_hp": 81,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561197999477537,
            "relic_choices": [
              {
                "choice": "RELIC.PAELS_HORN",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.PAEL",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "floor_added_to_deck": 18,
                  "id": "CARD.DEATH_MARCH"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.DRAIN_POWER"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.LEGION_OF_BONE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "current_upgrade_level": 1,
                "floor_added_to_deck": 18,
                "id": "CARD.DEATH_MARCH"
              }
            ],
            "current_gold": 212,
            "current_hp": 43,
            "damage_taken": 12,
            "gold_gained": 8,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 1,
            "max_hp": 63,
            "max_hp_gained": 1,
            "max_hp_lost": 0,
            "player_id": 76561198005465391,
            "potion_choices": [
              {
                "choice": "POTION.SWIFT_POTION",
                "was_picked": true
              }
            ],
            "potion_discarded": [
              "POTION.SPEED_POTION"
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 18,
                  "id": "CARD.STARDUST"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.CRESCENT_SPEAR"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.REFINE_BLADE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.STARDUST"
              }
            ],
            "current_gold": 284,
            "current_hp": 61,
            "damage_taken": 7,
            "gold_gained": 21,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 1,
            "max_hp": 82,
            "max_hp_gained": 1,
            "max_hp_lost": 0,
            "player_id": 76561197999477537,
            "potion_choices": [
              {
                "choice": "POTION.VULNERABLE_POTION",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.TUNNELER_WEAK",
            "monster_ids": [
              "MONSTER.TUNNELER"
            ],
            "room_type": "monster",
            "turns_taken": 5
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 19,
                  "id": "CARD.SCULPTING_STRIKE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.REAVE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.DEATH_MARCH"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 19,
                "id": "CARD.SCULPTING_STRIKE"
              }
            ],
            "current_gold": 225,
            "current_hp": 39,
            "damage_taken": 5,
            "gold_gained": 13,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 1,
            "max_hp": 64,
            "max_hp_gained": 1,
            "max_hp_lost": 0,
            "player_id": 76561198005465391
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 19,
                  "id": "CARD.KNOW_THY_PLACE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.CLOAK_OF_STARS"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.CELESTIAL_MIGHT"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.KNOW_THY_PLACE"
              }
            ],
            "current_gold": 304,
            "current_hp": 45,
            "damage_taken": 17,
            "gold_gained": 20,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 1,
            "max_hp": 83,
            "max_hp_gained": 1,
            "max_hp_lost": 0,
            "player_id": 76561197999477537,
            "potion_choices": [
              {
                "choice": "POTION.WEAK_POTION",
                "was_picked": false
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.BOWLBUGS_WEAK",
            "monster_ids": [
              "MONSTER.BOWLBUG_ROCK",
              "MONSTER.BOWLBUG_EGG"
            ],
            "room_type": "monster",
            "turns_taken": 4
          }
        ]
      },
      {
        "map_point_type": "shop",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "floor_added_to_deck": 20,
                  "id": "CARD.FRIENDSHIP"
                },
                "was_picked": true
              },
              {
                "card": {
                  "floor_added_to_deck": 20,
                  "id": "CARD.CAPTURE_SPIRIT"
                },
                "was_picked": true
              }
            ],
            "cards_gained": [
              {
                "current_upgrade_level": 1,
                "floor_added_to_deck": 20,
                "id": "CARD.FRIENDSHIP"
              },
              {
                "floor_added_to_deck": 20,
                "id": "CARD.CAPTURE_SPIRIT"
              }
            ],
            "cards_removed": [
              {
                "floor_added_to_deck": 1,
                "id": "CARD.STRIKE_NECROBINDER"
              }
            ],
            "current_gold": 10,
            "current_hp": 39,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 115,
            "gold_spent": 100,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 64,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198005465391
          },
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.DEVASTATE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.HEGEMONY"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.COSMIC_INDIFFERENCE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.FURNACE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.OMNISLICE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.BEAT_DOWN"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.HIDDEN_CACHE"
              }
            ],
            "cards_removed": [
              {
                "floor_added_to_deck": 1,
                "id": "CARD.STRIKE_REGENT"
              }
            ],
            "current_gold": 177,
            "current_hp": 60,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 127,
            "gold_stolen": 0,
            "hp_healed": 15,
            "max_hp": 83,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561197999477537,
            "potion_choices": [
              {
                "choice": "POTION.COLORLESS_POTION",
                "was_picked": false
              },
              {
                "choice": "POTION.ATTACK_POTION",
                "was_picked": false
              },
              {
                "choice": "POTION.WEAK_POTION",
                "was_picked": false
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.LETTER_OPENER",
                "was_picked": false
              },
              {
                "choice": "RELIC.JUZU_BRACELET",
                "was_picked": false
              },
              {
                "choice": "RELIC.THE_ABACUS",
                "was_picked": false
              }
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "shop",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "current_gold": 43,
            "current_hp": 39,
            "damage_taken": 0,
            "gold_gained": 33,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 64,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198005465391,
            "relic_choices": [
              {
                "choice": "RELIC.JUZU_BRACELET",
                "was_picked": true
              }
            ]
          },
          {
            "current_gold": 209,
            "current_hp": 60,
            "damage_taken": 0,
            "gold_gained": 32,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 83,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561197999477537,
            "relic_choices": [
              {
                "choice": "RELIC.ODDLY_SMOOTH_STONE",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "treasure",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "elite",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.SCOURGE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.HAUNT"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.SEVERANCE"
                },
                "was_picked": false
              }
            ],
            "current_gold": 70,
            "current_hp": 14,
            "damage_taken": 26,
            "gold_gained": 27,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 1,
            "max_hp": 65,
            "max_hp_gained": 1,
            "max_hp_lost": 0,
            "player_id": 76561198005465391,
            "potion_used": [
              "POTION.SWIFT_POTION"
            ],
            "relic_choices": [
              {
                "choice": "RELIC.BOOK_OF_FIVE_RINGS",
                "was_picked": true
              }
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 22,
                  "id": "CARD.BULWARK"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.PHOTON_CUT"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.CRESCENT_SPEAR"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.BULWARK"
              }
            ],
            "current_gold": 250,
            "current_hp": 31,
            "damage_taken": 30,
            "gold_gained": 41,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 1,
            "max_hp": 84,
            "max_hp_gained": 1,
            "max_hp_lost": 0,
            "player_id": 76561197999477537,
            "potion_used": [
              "POTION.VULNERABLE_POTION"
            ],
            "relic_choices": [
              {
                "choice": "RELIC.PENDULUM",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.DECIMILLIPEDE_ELITE",
            "monster_ids": [
              "MONSTER.DECIMILLIPEDE_SEGMENT_FRONT",
              "MONSTER.DECIMILLIPEDE_SEGMENT_MIDDLE",
              "MONSTER.DECIMILLIPEDE_SEGMENT_BACK"
            ],
            "room_type": "elite",
            "turns_taken": 4
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 70,
            "current_hp": 33,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 19,
            "max_hp": 65,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198005465391,
            "rest_site_choices": [
              "HEAL"
            ]
          },
          {
            "current_gold": 250,
            "current_hp": 31,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 84,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561197999477537,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.RELAX"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "treasure",
        "player_stats": [
          {
            "cards_removed": [
              {
                "floor_added_to_deck": 13,
                "id": "CARD.SPOILS_MAP",
                "props": {
                  "ints": [
                    {
                      "name": "SpoilsActIndex",
                      "value": 1
                    }
                  ]
                }
              }
            ],
            "completed_quests": [
              "CARD.SPOILS_MAP"
            ],
            "current_gold": 708,
            "current_hp": 33,
            "damage_taken": 0,
            "gold_gained": 638,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 65,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198005465391,
            "relic_choices": [
              {
                "choice": "RELIC.HORN_CLEAT",
                "was_picked": true
              }
            ]
          },
          {
            "cards_removed": [
              {
                "floor_added_to_deck": 13,
                "id": "CARD.SPOILS_MAP",
                "props": {
                  "ints": [
                    {
                      "name": "SpoilsActIndex",
                      "value": 1
                    }
                  ]
                }
              }
            ],
            "completed_quests": [
              "CARD.SPOILS_MAP"
            ],
            "current_gold": 883,
            "current_hp": 31,
            "damage_taken": 0,
            "gold_gained": 633,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 84,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561197999477537,
            "relic_choices": [
              {
                "choice": "RELIC.POCKETWATCH",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "treasure",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 708,
            "current_hp": 33,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 65,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198005465391,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.CAPTURE_SPIRIT"
            ]
          },
          {
            "current_gold": 883,
            "current_hp": 31,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 84,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561197999477537,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.RELAX"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "current_gold": 608,
            "current_hp": 33,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "WELCOME_TO_WONGOS.pages.INITIAL.options.BARGAIN_BIN.title",
                  "table": "events"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 100,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 65,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198005465391,
            "relic_choices": [
              {
                "choice": "RELIC.VENERABLE_TEA_SET",
                "was_picked": true
              }
            ]
          },
          {
            "current_gold": 783,
            "current_hp": 31,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "WELCOME_TO_WONGOS.pages.INITIAL.options.BARGAIN_BIN.title",
                  "table": "events"
                },
                "variables": {
                  "BargainBinCost": {
                    "type": "BaseDynamic",
                    "decimal_value": 100,
                    "bool_value": false,
                    "string_value": null
                  },
                  "MysteryBoxCost": {
                    "type": "BaseDynamic",
                    "decimal_value": 300,
                    "bool_value": false,
                    "string_value": null
                  },
                  "FeaturedItemCost": {
                    "type": "BaseDynamic",
                    "decimal_value": 200,
                    "bool_value": false,
                    "string_value": null
                  },
                  "MysteryBoxRelicCount": {
                    "type": "BaseDynamic",
                    "decimal_value": 3,
                    "bool_value": false,
                    "string_value": null
                  },
                  "MysteryBoxCombatCount": {
                    "type": "BaseDynamic",
                    "decimal_value": 5,
                    "bool_value": false,
                    "string_value": null
                  },
                  "WongoPointAmount": {
                    "type": "BaseDynamic",
                    "decimal_value": 48,
                    "bool_value": false,
                    "string_value": null
                  },
                  "RemainingWongoPointAmount": {
                    "type": "BaseDynamic",
                    "decimal_value": 1952,
                    "bool_value": false,
                    "string_value": null
                  },
                  "TotalWongoBadgeAmount": {
                    "type": "BaseDynamic",
                    "decimal_value": 0,
                    "bool_value": false,
                    "string_value": null
                  },
                  "RandomRelic": {
                    "type": "DynamicString",
                    "decimal_value": 0,
                    "bool_value": false,
                    "string_value": "White Beast Statue"
                  }
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 100,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 84,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561197999477537,
            "relic_choices": [
              {
                "choice": "RELIC.VAJRA",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.WELCOME_TO_WONGOS",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 608,
            "current_hp": 52,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 19,
            "max_hp": 65,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198005465391,
            "rest_site_choices": [
              "HEAL"
            ]
          },
          {
            "current_gold": 783,
            "current_hp": 56,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 25,
            "max_hp": 84,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561197999477537,
            "rest_site_choices": [
              "HEAL"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "cards_gained": [
              {
                "current_upgrade_level": 1,
                "id": "CARD.FRIENDSHIP"
              }
            ],
            "current_gold": 608,
            "current_hp": 52,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "INFESTED_AUTOMATON.pages.INITIAL.options.STUDY.title",
                  "table": "events"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 65,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198005465391
          },
          {
            "cards_gained": [
              {
                "id": "CARD.CHILD_OF_THE_STARS"
              }
            ],
            "current_gold": 783,
            "current_hp": 56,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "INFESTED_AUTOMATON.pages.INITIAL.options.STUDY.title",
                  "table": "events"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 84,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561197999477537
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.INFESTED_AUTOMATON",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "shop",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 29,
                  "id": "CARD.CAPTURE_SPIRIT"
                },
                "was_picked": true
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "floor_added_to_deck": 29,
                  "id": "CARD.PAGESTORM"
                },
                "was_picked": true
              },
              {
                "card": {
                  "floor_added_to_deck": 29,
                  "id": "CARD.INVOKE"
                },
                "was_picked": true
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 29,
                "id": "CARD.CAPTURE_SPIRIT"
              },
              {
                "current_upgrade_level": 1,
                "floor_added_to_deck": 29,
                "id": "CARD.PAGESTORM"
              },
              {
                "floor_added_to_deck": 29,
                "id": "CARD.INVOKE"
              }
            ],
            "current_gold": 16,
            "current_hp": 52,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 592,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 65,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198005465391,
            "relic_choices": [
              {
                "choice": "RELIC.BREAD",
                "was_picked": true
              },
              {
                "choice": "RELIC.GORGET",
                "was_picked": true
              }
            ]
          },
          {
            "bought_potions": [
              "POTION.SWIFT_POTION",
              "POTION.WEAK_POTION"
            ],
            "bought_relics": [
              "RELIC.DINGY_RUG",
              "RELIC.POTION_BELT"
            ],
            "card_choices": [
              {
                "card": {
                  "id": "CARD.KNOCKOUT_BLOW"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.BEGONE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.CLOAK_OF_STARS"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.CHILD_OF_THE_STARS"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.IMPATIENCE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.MIMIC"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.RESONANCE"
              }
            ],
            "cards_removed": [
              {
                "floor_added_to_deck": 1,
                "id": "CARD.STRIKE_REGENT"
              }
            ],
            "current_gold": 155,
            "current_hp": 71,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 628,
            "gold_stolen": 0,
            "hp_healed": 15,
            "max_hp": 84,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561197999477537,
            "potion_choices": [
              {
                "choice": "POTION.SWIFT_POTION",
                "was_picked": true
              },
              {
                "choice": "POTION.WEAK_POTION",
                "was_picked": true
              },
              {
                "choice": "POTION.COLORLESS_POTION",
                "was_picked": false
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.DINGY_RUG",
                "was_picked": true
              },
              {
                "choice": "RELIC.POTION_BELT",
                "was_picked": true
              },
              {
                "choice": "RELIC.ORNAMENTAL_FAN",
                "was_picked": false
              }
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "shop",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 16,
            "current_hp": 52,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 65,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198005465391,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.CAPTURE_SPIRIT"
            ]
          },
          {
            "current_gold": 155,
            "current_hp": 71,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 84,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561197999477537,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.VOID_FORM"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "boss",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 31,
                  "id": "CARD.TRANSFIGURE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.ERADICATE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.GLIMPSE_BEYOND"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 31,
                "id": "CARD.TRANSFIGURE"
              }
            ],
            "current_gold": 91,
            "current_hp": 62,
            "damage_taken": 6,
            "gold_gained": 75,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 16,
            "max_hp": 66,
            "max_hp_gained": 1,
            "max_hp_lost": 0,
            "player_id": 76561198005465391,
            "potion_choices": [
              {
                "choice": "POTION.FIRE_POTION",
                "was_picked": true
              }
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 31,
                  "id": "CARD.ROLLING_BOULDER"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.BOLAS"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.ALCHEMIZE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.ROLLING_BOULDER"
              }
            ],
            "current_gold": 240,
            "current_hp": 53,
            "damage_taken": 19,
            "gold_gained": 85,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 1,
            "max_hp": 85,
            "max_hp_gained": 1,
            "max_hp_lost": 0,
            "player_id": 76561197999477537
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.KAISER_CRAB_BOSS",
            "monster_ids": [
              "MONSTER.CRUSHER",
              "MONSTER.ROCKET"
            ],
            "room_type": "boss",
            "turns_taken": 9
          }
        ]
      }
    ],
    [
      {
        "map_point_type": "ancient",
        "player_stats": [
          {
            "ancient_choice": [
              {
                "TextKey": "SAI",
                "title": {
                  "key": "SAI.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "MEAT_CLEAVER",
                "title": {
                  "key": "MEAT_CLEAVER.title",
                  "table": "relics"
                },
                "was_chosen": true
              },
              {
                "TextKey": "CROSSBOW",
                "title": {
                  "key": "CROSSBOW.title",
                  "table": "relics"
                },
                "was_chosen": false
              }
            ],
            "current_gold": 91,
            "current_hp": 65,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "MEAT_CLEAVER.title",
                  "table": "relics"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 3,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198005465391,
            "relic_choices": [
              {
                "choice": "RELIC.MEAT_CLEAVER",
                "was_picked": true
              }
            ]
          },
          {
            "ancient_choice": [
              {
                "TextKey": "TRI_BOOMERANG",
                "title": {
                  "key": "TRI_BOOMERANG.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "IRON_CLUB",
                "title": {
                  "key": "IRON_CLUB.title",
                  "table": "relics"
                },
                "was_chosen": true
              },
              {
                "TextKey": "MEAT_CLEAVER",
                "title": {
                  "key": "MEAT_CLEAVER.title",
                  "table": "relics"
                },
                "was_chosen": false
              }
            ],
            "current_gold": 240,
            "current_hp": 78,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "IRON_CLUB.title",
                  "table": "relics"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 25,
            "max_hp": 85,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561197999477537,
            "relic_choices": [
              {
                "choice": "RELIC.IRON_CLUB",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.TANX",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "floor_added_to_deck": 33,
                  "id": "CARD.GRAVEBLAST"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.SCOURGE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.SNAP"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "current_upgrade_level": 1,
                "floor_added_to_deck": 33,
                "id": "CARD.GRAVEBLAST"
              }
            ],
            "current_gold": 106,
            "current_hp": 61,
            "damage_taken": 5,
            "gold_gained": 15,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 1,
            "max_hp": 65,
            "max_hp_gained": 1,
            "max_hp_lost": 2,
            "player_id": 76561198005465391,
            "potion_choices": [
              {
                "choice": "POTION.SKILL_POTION",
                "was_picked": true
              }
            ],
            "potion_discarded": [
              "POTION.STRENGTH_POTION"
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 33,
                  "id": "CARD.AUTOMATION"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.SPOILS_OF_BATTLE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.GLOW"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.AUTOMATION"
              }
            ],
            "current_gold": 257,
            "current_hp": 77,
            "damage_taken": 2,
            "gold_gained": 17,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 1,
            "max_hp": 84,
            "max_hp_gained": 1,
            "max_hp_lost": 2,
            "player_id": 76561197999477537,
            "potion_choices": [
              {
                "choice": "POTION.FORTIFIER",
                "was_picked": true
              }
            ],
            "potion_used": [
              "POTION.WEAK_POTION"
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.SCROLLS_OF_BITING_WEAK",
            "monster_ids": [
              "MONSTER.SCROLL_OF_BITING",
              "MONSTER.SCROLL_OF_BITING",
              "MONSTER.SCROLL_OF_BITING"
            ],
            "room_type": "monster",
            "turns_taken": 5
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "floor_added_to_deck": 34,
                  "id": "CARD.DREDGE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.BLIGHT_STRIKE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.CAPTURE_SPIRIT"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "current_upgrade_level": 1,
                "floor_added_to_deck": 34,
                "id": "CARD.DREDGE"
              }
            ],
            "current_gold": 119,
            "current_hp": 62,
            "damage_taken": 0,
            "gold_gained": 13,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 1,
            "max_hp": 66,
            "max_hp_gained": 1,
            "max_hp_lost": 0,
            "player_id": 76561198005465391,
            "potion_used": [
              "POTION.SKILL_POTION"
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 34,
                  "id": "CARD.CHARGE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.BEGONE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.CHILD_OF_THE_STARS"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.CHARGE"
              }
            ],
            "current_gold": 278,
            "current_hp": 58,
            "damage_taken": 20,
            "gold_gained": 21,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 1,
            "max_hp": 85,
            "max_hp_gained": 1,
            "max_hp_lost": 0,
            "player_id": 76561197999477537
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.TURRET_OPERATOR_WEAK",
            "monster_ids": [
              "MONSTER.LIVING_SHIELD",
              "MONSTER.TURRET_OPERATOR"
            ],
            "room_type": "monster",
            "turns_taken": 5
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 35,
                  "id": "CARD.DEFY"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.PUTREFY"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.POKE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 35,
                "id": "CARD.DEFY"
              }
            ],
            "current_gold": 134,
            "current_hp": 53,
            "damage_taken": 10,
            "gold_gained": 15,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 1,
            "max_hp": 67,
            "max_hp_gained": 1,
            "max_hp_lost": 0,
            "player_id": 76561198005465391,
            "potion_used": [
              "POTION.FIRE_POTION"
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "floor_added_to_deck": 35,
                  "id": "CARD.COLLISION_COURSE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.SPOILS_OF_BATTLE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.BEGONE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "current_upgrade_level": 1,
                "id": "CARD.COLLISION_COURSE"
              }
            ],
            "current_gold": 299,
            "current_hp": 56,
            "damage_taken": 3,
            "gold_gained": 21,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 1,
            "max_hp": 86,
            "max_hp_gained": 1,
            "max_hp_lost": 0,
            "player_id": 76561197999477537
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.GLOBE_HEAD_NORMAL",
            "monster_ids": [
              "MONSTER.GLOBE_HEAD"
            ],
            "room_type": "monster",
            "turns_taken": 5
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.SHROUD"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.SCULPTING_STRIKE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.REAP"
                },
                "was_picked": false
              }
            ],
            "current_gold": 146,
            "current_hp": 54,
            "damage_taken": 0,
            "gold_gained": 12,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 1,
            "max_hp": 68,
            "max_hp_gained": 1,
            "max_hp_lost": 0,
            "player_id": 76561198005465391
          },
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "floor_added_to_deck": 36,
                  "id": "CARD.THINKING_AHEAD"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.GATHER_LIGHT"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.SPECTRUM_SHIFT"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "current_upgrade_level": 1,
                "id": "CARD.THINKING_AHEAD"
              }
            ],
            "current_gold": 316,
            "current_hp": 47,
            "damage_taken": 10,
            "gold_gained": 17,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 1,
            "max_hp": 87,
            "max_hp_gained": 1,
            "max_hp_lost": 0,
            "player_id": 76561197999477537,
            "potion_choices": [
              {
                "choice": "POTION.STABLE_SERUM",
                "was_picked": true
              }
            ],
            "potion_used": [
              "POTION.FORTIFIER"
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.THE_LOST_AND_FORGOTTEN_NORMAL",
            "monster_ids": [
              "MONSTER.THE_LOST",
              "MONSTER.THE_FORGOTTEN"
            ],
            "room_type": "monster",
            "turns_taken": 6
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "cards_removed": [
              {
                "floor_added_to_deck": 1,
                "id": "CARD.STRIKE_NECROBINDER"
              },
              {
                "floor_added_to_deck": 10,
                "id": "CARD.DEFILE"
              }
            ],
            "current_gold": 146,
            "current_hp": 63,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 9,
            "max_hp": 77,
            "max_hp_gained": 9,
            "max_hp_lost": 0,
            "player_id": 76561198005465391,
            "rest_site_choices": [
              "COOK"
            ]
          },
          {
            "current_gold": 316,
            "current_hp": 47,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 87,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561197999477537,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.AUTOMATION"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "treasure",
        "player_stats": [
          {
            "current_gold": 178,
            "current_hp": 63,
            "damage_taken": 0,
            "gold_gained": 32,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 77,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198005465391,
            "relic_choices": [
              {
                "choice": "RELIC.LANTERN",
                "was_picked": true
              }
            ]
          },
          {
            "current_gold": 355,
            "current_hp": 47,
            "damage_taken": 0,
            "gold_gained": 39,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 87,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561197999477537,
            "relic_choices": [
              {
                "choice": "RELIC.WAR_PAINT",
                "was_picked": true
              }
            ],
            "upgraded_cards": [
              "CARD.DEFEND_REGENT",
              "CARD.CHARGE"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "treasure",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "elite",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.INVOKE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.BURY"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.SOW"
                },
                "was_picked": false
              }
            ],
            "current_gold": 211,
            "current_hp": 64,
            "damage_taken": 0,
            "gold_gained": 33,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 1,
            "max_hp": 78,
            "max_hp_gained": 1,
            "max_hp_lost": 0,
            "player_id": 76561198005465391,
            "potion_choices": [
              {
                "choice": "POTION.COLORLESS_POTION",
                "was_picked": true
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.BELLOWS",
                "was_picked": true
              }
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.KNOW_THY_PLACE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.CELESTIAL_MIGHT"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.INTERCEPT"
                },
                "was_picked": false
              }
            ],
            "current_gold": 394,
            "current_hp": 24,
            "damage_taken": 24,
            "gold_gained": 39,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 1,
            "max_hp": 88,
            "max_hp_gained": 1,
            "max_hp_lost": 0,
            "player_id": 76561197999477537,
            "relic_choices": [
              {
                "choice": "RELIC.REGAL_PILLOW",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.SOUL_NEXUS_ELITE",
            "monster_ids": [
              "MONSTER.SOUL_NEXUS"
            ],
            "room_type": "elite",
            "turns_taken": 5
          }
        ]
      },
      {
        "map_point_type": "shop",
        "player_stats": [
          {
            "cards_removed": [
              {
                "floor_added_to_deck": 19,
                "id": "CARD.SCULPTING_STRIKE"
              }
            ],
            "current_gold": 37,
            "current_hp": 64,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 49,
            "gold_spent": 125,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 78,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198005465391,
            "potion_choices": [
              {
                "choice": "POTION.ENERGY_POTION",
                "was_picked": true
              }
            ]
          },
          {
            "bought_potions": [
              "POTION.DROPLET_OF_PRECOGNITION"
            ],
            "card_choices": [
              {
                "card": {
                  "id": "CARD.SUPERMASSIVE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.CRUSH_UNDER"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.CLOAK_OF_STARS"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.CHILD_OF_THE_STARS"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.ULTIMATE_STRIKE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.SALVO"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.GUARDS"
              }
            ],
            "cards_removed": [
              {
                "floor_added_to_deck": 1,
                "id": "CARD.STRIKE_REGENT"
              }
            ],
            "current_gold": 22,
            "current_hp": 39,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 372,
            "gold_stolen": 0,
            "hp_healed": 15,
            "max_hp": 88,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561197999477537,
            "potion_choices": [
              {
                "choice": "POTION.DROPLET_OF_PRECOGNITION",
                "was_picked": true
              },
              {
                "choice": "POTION.ENERGY_POTION",
                "was_picked": false
              },
              {
                "choice": "POTION.FORTIFIER",
                "was_picked": false
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.KUSARIGAMA",
                "was_picked": false
              },
              {
                "choice": "RELIC.STRAWBERRY",
                "was_picked": false
              },
              {
                "choice": "RELIC.GHOST_SEED",
                "was_picked": false
              }
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "shop",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "elite",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.PUTREFY"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.PULL_AGGRO"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.REAP"
                },
                "was_picked": false
              }
            ],
            "current_gold": 66,
            "current_hp": 65,
            "damage_taken": 0,
            "gold_gained": 29,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 1,
            "max_hp": 79,
            "max_hp_gained": 1,
            "max_hp_lost": 0,
            "player_id": 76561198005465391,
            "potion_choices": [
              {
                "choice": "POTION.ATTACK_POTION",
                "was_picked": true
              }
            ],
            "potion_used": [
              "POTION.COLORLESS_POTION"
            ],
            "relic_choices": [
              {
                "choice": "RELIC.PENDULUM",
                "was_picked": true
              }
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 41,
                  "id": "CARD.CONVERGENCE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.CELESTIAL_MIGHT"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.CRUSH_UNDER"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.CONVERGENCE"
              }
            ],
            "current_gold": 62,
            "current_hp": 13,
            "damage_taken": 27,
            "gold_gained": 40,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 1,
            "max_hp": 89,
            "max_hp_gained": 1,
            "max_hp_lost": 0,
            "player_id": 76561197999477537,
            "potion_choices": [
              {
                "choice": "POTION.ATTACK_POTION",
                "was_picked": false
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.BAG_OF_PREPARATION",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.KNIGHTS_ELITE",
            "monster_ids": [
              "MONSTER.FLAIL_KNIGHT",
              "MONSTER.SPECTRAL_KNIGHT",
              "MONSTER.MAGI_KNIGHT"
            ],
            "room_type": "elite",
            "turns_taken": 5
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "floor_added_to_deck": 42,
                  "id": "CARD.DEVOUR_LIFE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.PARSE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.BLIGHT_STRIKE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "current_upgrade_level": 1,
                "floor_added_to_deck": 42,
                "id": "CARD.DEVOUR_LIFE"
              }
            ],
            "current_gold": 79,
            "current_hp": 33,
            "damage_taken": 33,
            "gold_gained": 13,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 1,
            "max_hp": 68,
            "max_hp_gained": 1,
            "max_hp_lost": 12,
            "player_id": 76561198005465391,
            "potion_choices": [
              {
                "choice": "POTION.COLORLESS_POTION",
                "was_picked": true
              }
            ],
            "potion_used": [
              "POTION.ENERGY_POTION",
              "POTION.ATTACK_POTION"
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.WROUGHT_IN_WAR"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.SOLAR_STRIKE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.GLOW"
                },
                "was_picked": false
              }
            ],
            "current_gold": 84,
            "current_hp": 2,
            "damage_taken": 13,
            "gold_gained": 22,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 2,
            "max_hp": 84,
            "max_hp_gained": 1,
            "max_hp_lost": 6,
            "player_id": 76561197999477537,
            "potion_choices": [
              {
                "choice": "POTION.SKILL_POTION",
                "was_picked": true
              }
            ],
            "potion_used": [
              "POTION.SWIFT_POTION"
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.SCROLLS_OF_BITING_NORMAL",
            "monster_ids": [
              "MONSTER.SCROLL_OF_BITING",
              "MONSTER.SCROLL_OF_BITING",
              "MONSTER.SCROLL_OF_BITING",
              "MONSTER.SCROLL_OF_BITING"
            ],
            "room_type": "monster",
            "turns_taken": 6
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.DEATH_MARCH"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.NEGATIVE_PULSE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.FLATTEN"
                },
                "was_picked": false
              }
            ],
            "current_gold": 92,
            "current_hp": 34,
            "damage_taken": 0,
            "gold_gained": 13,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 1,
            "max_hp": 69,
            "max_hp_gained": 1,
            "max_hp_lost": 0,
            "player_id": 76561198005465391
          },
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "floor_added_to_deck": 43,
                  "id": "CARD.PHOTON_CUT"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.HIDDEN_CACHE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.CRESCENT_SPEAR"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "current_upgrade_level": 1,
                "id": "CARD.PHOTON_CUT"
              }
            ],
            "current_gold": 101,
            "current_hp": 2,
            "damage_taken": 2,
            "gold_gained": 17,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 2,
            "max_hp": 85,
            "max_hp_gained": 1,
            "max_hp_lost": 0,
            "player_id": 76561197999477537
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.AXEBOTS_NORMAL",
            "monster_ids": [
              "MONSTER.AXEBOT",
              "MONSTER.AXEBOT"
            ],
            "room_type": "monster",
            "turns_taken": 7
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "cards_removed": [
              {
                "floor_added_to_deck": 1,
                "id": "CARD.SOW"
              },
              {
                "floor_added_to_deck": 1,
                "id": "CARD.BODYGUARD"
              }
            ],
            "current_gold": 92,
            "current_hp": 43,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 9,
            "max_hp": 78,
            "max_hp_gained": 9,
            "max_hp_lost": 0,
            "player_id": 76561198005465391,
            "rest_site_choices": [
              "COOK"
            ]
          },
          {
            "current_gold": 101,
            "current_hp": 42,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 40,
            "max_hp": 85,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561197999477537,
            "rest_site_choices": [
              "HEAL"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "boss",
        "player_stats": [
          {
            "current_gold": 92,
            "current_hp": 41,
            "damage_taken": 3,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 1,
            "max_hp": 79,
            "max_hp_gained": 1,
            "max_hp_lost": 0,
            "player_id": 76561198005465391,
            "potion_used": [
              "POTION.COLORLESS_POTION"
            ]
          },
          {
            "current_gold": 101,
            "current_hp": 41,
            "damage_taken": 2,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 1,
            "max_hp": 86,
            "max_hp_gained": 1,
            "max_hp_lost": 0,
            "player_id": 76561197999477537,
            "potion_used": [
              "POTION.SKILL_POTION",
              "POTION.DUPLICATOR",
              "POTION.DROPLET_OF_PRECOGNITION",
              "POTION.STABLE_SERUM"
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.DOORMAKER_BOSS",
            "monster_ids": [
              "MONSTER.DOOR"
            ],
            "room_type": "boss",
            "turns_taken": 7
          }
        ]
      }
    ]
  ],
  "modifiers": [],
  "platform_type": "steam",
  "players": [
    {
      "character": "CHARACTER.NECROBINDER",
      "deck": [
        {
          "enchantment": {
            "amount": 14,
            "id": "ENCHANTMENT.GOOPY"
          },
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_NECROBINDER"
        },
        {
          "enchantment": {
            "amount": 10,
            "id": "ENCHANTMENT.GOOPY"
          },
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_NECROBINDER"
        },
        {
          "enchantment": {
            "amount": 14,
            "id": "ENCHANTMENT.GOOPY"
          },
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_NECROBINDER"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.UNLEASH"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.ASCENDERS_BANE"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.LEGION_OF_BONE"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 2,
          "id": "CARD.REAVE"
        },
        {
          "floor_added_to_deck": 4,
          "id": "CARD.VEILPIERCER"
        },
        {
          "floor_added_to_deck": 5,
          "id": "CARD.CLEANSE"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 7,
          "id": "CARD.HAUNT"
        },
        {
          "floor_added_to_deck": 14,
          "id": "CARD.SEVERANCE"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 16,
          "id": "CARD.CALL_OF_THE_VOID"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 18,
          "id": "CARD.DEATH_MARCH"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 20,
          "id": "CARD.FRIENDSHIP"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 20,
          "id": "CARD.CAPTURE_SPIRIT"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 28,
          "id": "CARD.FRIENDSHIP"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 29,
          "id": "CARD.CAPTURE_SPIRIT"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 29,
          "id": "CARD.PAGESTORM"
        },
        {
          "floor_added_to_deck": 29,
          "id": "CARD.INVOKE"
        },
        {
          "floor_added_to_deck": 31,
          "id": "CARD.TRANSFIGURE"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 33,
          "id": "CARD.GRAVEBLAST"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 34,
          "id": "CARD.DREDGE"
        },
        {
          "floor_added_to_deck": 35,
          "id": "CARD.DEFY"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 42,
          "id": "CARD.DEVOUR_LIFE"
        }
      ],
      "id": 76561198005465391,
      "max_potion_slot_count": 2,
      "potions": [],
      "relics": [
        {
          "floor_added_to_deck": 1,
          "id": "RELIC.BOUND_PHYLACTERY"
        },
        {
          "floor_added_to_deck": 1,
          "id": "RELIC.LEAFY_POULTICE"
        },
        {
          "floor_added_to_deck": 3,
          "id": "RELIC.CHOSEN_CHEESE"
        },
        {
          "floor_added_to_deck": 7,
          "id": "RELIC.FROZEN_EGG"
        },
        {
          "floor_added_to_deck": 9,
          "id": "RELIC.PERMAFROST"
        },
        {
          "floor_added_to_deck": 10,
          "id": "RELIC.HAPPY_FLOWER",
          "props": {
            "ints": [
              {
                "name": "TurnsSeen",
                "value": 1
              }
            ]
          }
        },
        {
          "floor_added_to_deck": 11,
          "id": "RELIC.DARKSTONE_PERIAPT"
        },
        {
          "floor_added_to_deck": 14,
          "id": "RELIC.ANCHOR"
        },
        {
          "floor_added_to_deck": 17,
          "id": "RELIC.PAELS_CLAW"
        },
        {
          "floor_added_to_deck": 21,
          "id": "RELIC.JUZU_BRACELET"
        },
        {
          "floor_added_to_deck": 22,
          "id": "RELIC.BOOK_OF_FIVE_RINGS",
          "props": {
            "ints": [
              {
                "name": "CardsAdded",
                "value": 9
              }
            ]
          }
        },
        {
          "floor_added_to_deck": 24,
          "id": "RELIC.HORN_CLEAT"
        },
        {
          "floor_added_to_deck": 26,
          "id": "RELIC.VENERABLE_TEA_SET",
          "props": {
            "bools": [
              {
                "name": "GainEnergyInNextCombat",
                "value": false
              }
            ]
          }
        },
        {
          "floor_added_to_deck": 29,
          "id": "RELIC.BREAD"
        },
        {
          "floor_added_to_deck": 29,
          "id": "RELIC.GORGET"
        },
        {
          "floor_added_to_deck": 32,
          "id": "RELIC.MEAT_CLEAVER"
        },
        {
          "floor_added_to_deck": 38,
          "id": "RELIC.LANTERN"
        },
        {
          "floor_added_to_deck": 39,
          "id": "RELIC.BELLOWS"
        },
        {
          "floor_added_to_deck": 41,
          "id": "RELIC.PENDULUM"
        }
      ]
    },
    {
      "character": "CHARACTER.REGENT",
      "deck": [
        {
          "floor_added_to_deck": 1,
          "id": "CARD.STRIKE_REGENT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_REGENT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_REGENT"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_REGENT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_REGENT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.FALLING_STAR"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 1,
          "id": "CARD.VENERATE"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.ASCENDERS_BANE"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.BELIEVE_IN_YOU"
        },
        {
          "floor_added_to_deck": 2,
          "id": "CARD.ASTRAL_PULSE"
        },
        {
          "floor_added_to_deck": 4,
          "id": "CARD.PHOTON_CUT"
        },
        {
          "floor_added_to_deck": 5,
          "id": "CARD.CHILD_OF_THE_STARS"
        },
        {
          "floor_added_to_deck": 7,
          "id": "CARD.REFLECT"
        },
        {
          "floor_added_to_deck": 10,
          "id": "CARD.ALIGNMENT"
        },
        {
          "floor_added_to_deck": 14,
          "id": "CARD.WROUGHT_IN_WAR"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 16,
          "id": "CARD.VOID_FORM"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 17,
          "id": "CARD.RELAX"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 17,
          "id": "CARD.RELAX"
        },
        {
          "floor_added_to_deck": 18,
          "id": "CARD.STARDUST"
        },
        {
          "floor_added_to_deck": 19,
          "id": "CARD.KNOW_THY_PLACE"
        },
        {
          "floor_added_to_deck": 20,
          "id": "CARD.HIDDEN_CACHE"
        },
        {
          "floor_added_to_deck": 22,
          "id": "CARD.BULWARK"
        },
        {
          "floor_added_to_deck": 28,
          "id": "CARD.CHILD_OF_THE_STARS"
        },
        {
          "floor_added_to_deck": 29,
          "id": "CARD.RESONANCE"
        },
        {
          "floor_added_to_deck": 31,
          "id": "CARD.ROLLING_BOULDER"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 33,
          "id": "CARD.AUTOMATION"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 34,
          "id": "CARD.CHARGE"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 35,
          "id": "CARD.COLLISION_COURSE"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 36,
          "id": "CARD.THINKING_AHEAD"
        },
        {
          "floor_added_to_deck": 40,
          "id": "CARD.GUARDS"
        },
        {
          "floor_added_to_deck": 41,
          "id": "CARD.CONVERGENCE"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 43,
          "id": "CARD.PHOTON_CUT"
        }
      ],
      "id": 76561197999477537,
      "max_potion_slot_count": 4,
      "potions": [],
      "relics": [
        {
          "floor_added_to_deck": 1,
          "id": "RELIC.DIVINE_RIGHT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "RELIC.MASSIVE_SCROLL"
        },
        {
          "floor_added_to_deck": 3,
          "id": "RELIC.CHOSEN_CHEESE"
        },
        {
          "floor_added_to_deck": 7,
          "id": "RELIC.MEAL_TICKET"
        },
        {
          "floor_added_to_deck": 9,
          "id": "RELIC.AMETHYST_AUBERGINE"
        },
        {
          "floor_added_to_deck": 10,
          "id": "RELIC.FENCING_MANUAL"
        },
        {
          "floor_added_to_deck": 11,
          "id": "RELIC.HAND_DRILL"
        },
        {
          "floor_added_to_deck": 14,
          "id": "RELIC.BRONZE_SCALES"
        },
        {
          "floor_added_to_deck": 17,
          "id": "RELIC.PAELS_HORN"
        },
        {
          "floor_added_to_deck": 21,
          "id": "RELIC.ODDLY_SMOOTH_STONE"
        },
        {
          "floor_added_to_deck": 22,
          "id": "RELIC.PENDULUM"
        },
        {
          "floor_added_to_deck": 24,
          "id": "RELIC.POCKETWATCH"
        },
        {
          "floor_added_to_deck": 26,
          "id": "RELIC.VAJRA"
        },
        {
          "floor_added_to_deck": 29,
          "id": "RELIC.DINGY_RUG"
        },
        {
          "floor_added_to_deck": 29,
          "id": "RELIC.POTION_BELT"
        },
        {
          "floor_added_to_deck": 32,
          "id": "RELIC.IRON_CLUB",
          "props": {
            "ints": [
              {
                "name": "CardsPlayed",
                "value": 216
              }
            ]
          }
        },
        {
          "floor_added_to_deck": 38,
          "id": "RELIC.WAR_PAINT"
        },
        {
          "floor_added_to_deck": 39,
          "id": "RELIC.REGAL_PILLOW"
        },
        {
          "floor_added_to_deck": 41,
          "id": "RELIC.BAG_OF_PREPARATION"
        }
      ]
    }
  ],
  "run_time": 4501,
  "schema_version": 8,
  "seed": "2K6K1P34RQ",
  "start_time": 1772927940,
  "was_abandoned": false,
  "win": true
}