{
  "acts": [
    "ACT.OVERGROWTH",
    "ACT.HIVE",
    "ACT.GLORY"
  ],
  "ascension": 10,
  "build_id": "v0.102.0",
  "game_mode": "standard",
  "killed_by_encounter": "NONE.NONE",
  "killed_by_event": "NONE.NONE",
  "map_point_history": [
    [
      {
        "map_point_type": "ancient",
        "player_stats": [
          {
            "ancient_choice": [
              {
                "TextKey": "LEAD_PAPERWEIGHT",
                "title": {
                  "key": "LEAD_PAPERWEIGHT.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "GOLDEN_PEARL",
                "title": {
                  "key": "GOLDEN_PEARL.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "SCROLL_BOXES",
                "title": {
                  "key": "SCROLL_BOXES.title",
                  "table": "relics"
                },
                "was_chosen": true
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.BARRAGE"
              },
              {
                "id": "CARD.BEAM_CELL"
              },
              {
                "id": "CARD.WHITE_NOISE"
              }
            ],
            "current_gold": 0,
            "current_hp": 60,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "SCROLL_BOXES.title",
                  "table": "relics"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 99,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 60,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198218717931,
            "relic_choices": [
              {
                "choice": "RELIC.SCROLL_BOXES",
                "was_picked": true
              }
            ]
          },
          {
            "ancient_choice": [
              {
                "TextKey": "GOLDEN_PEARL",
                "title": {
                  "key": "GOLDEN_PEARL.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "LOST_COFFER",
                "title": {
                  "key": "LOST_COFFER.title",
                  "table": "relics"
                },
                "was_chosen": true
              },
              {
                "TextKey": "HEFTY_TABLET",
                "title": {
                  "key": "HEFTY_TABLET.title",
                  "table": "relics"
                },
                "was_chosen": false
              }
            ],
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 1,
                  "id": "CARD.LEAP"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.SWEEPING_BEAM"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.BEAM_CELL"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.LEAP"
              }
            ],
            "current_gold": 99,
            "current_hp": 60,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "LOST_COFFER.title",
                  "table": "relics"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 60,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561197999477537,
            "potion_choices": [
              {
                "choice": "POTION.RADIANT_TINCTURE",
                "was_picked": true
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.LOST_COFFER",
                "was_picked": true
              }
            ]
          },
          {
            "ancient_choice": [
              {
                "TextKey": "ARCANE_SCROLL",
                "title": {
                  "key": "ARCANE_SCROLL.title",
                  "table": "relics"
                },
                "was_chosen": true
              },
              {
                "TextKey": "BOOMING_CONCH",
                "title": {
                  "key": "BOOMING_CONCH.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "PRECARIOUS_SHEARS",
                "title": {
                  "key": "PRECARIOUS_SHEARS.title",
                  "table": "relics"
                },
                "was_chosen": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.ECHO_FORM"
              }
            ],
            "current_gold": 99,
            "current_hp": 60,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "ARCANE_SCROLL.title",
                  "table": "relics"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 60,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198005465391,
            "relic_choices": [
              {
                "choice": "RELIC.ARCANE_SCROLL",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.NEOW",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 2,
                  "id": "CARD.TURBO"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.SYNCHRONIZE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.BARRAGE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 2,
                "id": "CARD.TURBO"
              }
            ],
            "current_gold": 8,
            "current_hp": 59,
            "damage_taken": 1,
            "gold_gained": 8,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198218717931,
            "potion_choices": [
              {
                "choice": "POTION.COLORLESS_POTION",
                "was_picked": true
              }
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 2,
                  "id": "CARD.LOOP"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.SKIM"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.FUSION"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.LOOP"
              }
            ],
            "current_gold": 108,
            "current_hp": 52,
            "damage_taken": 8,
            "gold_gained": 9,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561197999477537
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 2,
                  "id": "CARD.UPROAR"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.BOOST_AWAY"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.CHARGE_BATTERY"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 2,
                "id": "CARD.UPROAR"
              }
            ],
            "current_gold": 114,
            "current_hp": 60,
            "damage_taken": 0,
            "gold_gained": 15,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198005465391
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.SHRINKER_BEETLE_WEAK",
            "monster_ids": [
              "MONSTER.SHRINKER_BEETLE"
            ],
            "room_type": "monster",
            "turns_taken": 3
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 3,
                  "id": "CARD.NULL"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.HOTFIX"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.CLAW"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 3,
                "id": "CARD.NULL"
              }
            ],
            "current_gold": 17,
            "current_hp": 51,
            "damage_taken": 8,
            "gold_gained": 9,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198218717931
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 3,
                  "id": "CARD.FOCUSED_STRIKE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.BULK_UP"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.CHARGE_BATTERY"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.FOCUSED_STRIKE"
              }
            ],
            "current_gold": 121,
            "current_hp": 48,
            "damage_taken": 4,
            "gold_gained": 13,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561197999477537,
            "potion_choices": [
              {
                "choice": "POTION.POWER_POTION",
                "was_picked": true
              }
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 3,
                  "id": "CARD.ROCKET_PUNCH"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.BARRAGE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.CLAW"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 3,
                "id": "CARD.ROCKET_PUNCH"
              }
            ],
            "current_gold": 125,
            "current_hp": 48,
            "damage_taken": 12,
            "gold_gained": 11,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198005465391
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.SLIMES_WEAK",
            "monster_ids": [
              "MONSTER.TWIG_SLIME_S",
              "MONSTER.LEAF_SLIME_M",
              "MONSTER.LEAF_SLIME_S"
            ],
            "room_type": "monster",
            "turns_taken": 5
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "cards_enchanted": [
              {
                "card": {
                  "enchantment": {
                    "amount": 1,
                    "id": "ENCHANTMENT.SLITHER"
                  },
                  "floor_added_to_deck": 3,
                  "id": "CARD.NULL"
                },
                "enchantment": "ENCHANTMENT.SLITHER"
              }
            ],
            "current_gold": 17,
            "current_hp": 51,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "WOOD_CARVINGS.pages.INITIAL.options.SNAKE.title",
                  "table": "events"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198218717931
          },
          {
            "cards_transformed": [
              {
                "final_card": {
                  "floor_added_to_deck": 4,
                  "id": "CARD.TORIC_TOUGHNESS"
                },
                "original_card": {
                  "floor_added_to_deck": 1,
                  "id": "CARD.STRIKE_DEFECT"
                }
              }
            ],
            "current_gold": 121,
            "current_hp": 48,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "WOOD_CARVINGS.pages.INITIAL.options.TORUS.title",
                  "table": "events"
                },
                "variables": {
                  "BirdCard": {
                    "type": "DynamicString",
                    "decimal_value": 0,
                    "bool_value": false,
                    "string_value": "Peck"
                  },
                  "SnakeEnchantment": {
                    "type": "DynamicString",
                    "decimal_value": 0,
                    "bool_value": false,
                    "string_value": "Slither"
                  },
                  "ToricCard": {
                    "type": "DynamicString",
                    "decimal_value": 0,
                    "bool_value": false,
                    "string_value": "Toric Toughness"
                  }
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561197999477537
          },
          {
            "cards_enchanted": [
              {
                "card": {
                  "enchantment": {
                    "amount": 1,
                    "id": "ENCHANTMENT.SLITHER"
                  },
                  "floor_added_to_deck": 1,
                  "id": "CARD.ECHO_FORM"
                },
                "enchantment": "ENCHANTMENT.SLITHER"
              }
            ],
            "current_gold": 125,
            "current_hp": 48,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "WOOD_CARVINGS.pages.INITIAL.options.SNAKE.title",
                  "table": "events"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198005465391
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.WOOD_CARVINGS",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 5,
                  "id": "CARD.HOLOGRAM"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.CLAW"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.GUNK_UP"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 5,
                "id": "CARD.HOLOGRAM"
              }
            ],
            "current_gold": 31,
            "current_hp": 48,
            "damage_taken": 3,
            "gold_gained": 14,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198218717931
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 5,
                  "id": "CARD.NULL"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.UPROAR"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.COMPILE_DRIVER"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.NULL"
              }
            ],
            "current_gold": 130,
            "current_hp": 40,
            "damage_taken": 8,
            "gold_gained": 9,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561197999477537,
            "potion_choices": [
              {
                "choice": "POTION.LIQUID_BRONZE",
                "was_picked": false
              }
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 5,
                  "id": "CARD.SWEEPING_BEAM"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.HOLOGRAM"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.FUSION"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 5,
                "id": "CARD.SWEEPING_BEAM"
              }
            ],
            "current_gold": 140,
            "current_hp": 40,
            "damage_taken": 8,
            "gold_gained": 15,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198005465391,
            "potion_choices": [
              {
                "choice": "POTION.DEXTERITY_POTION",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.NIBBITS_WEAK",
            "monster_ids": [
              "MONSTER.NIBBIT"
            ],
            "room_type": "monster",
            "turns_taken": 4
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 6,
                  "id": "CARD.CHARGE_BATTERY"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.UPROAR"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.SWEEPING_BEAM"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 6,
                "id": "CARD.CHARGE_BATTERY"
              }
            ],
            "current_gold": 44,
            "current_hp": 32,
            "damage_taken": 16,
            "gold_gained": 13,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198218717931
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 6,
                  "id": "CARD.COMPACT"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.SWEEPING_BEAM"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.COLD_SNAP"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.COMPACT"
              }
            ],
            "current_gold": 138,
            "current_hp": 36,
            "damage_taken": 4,
            "gold_gained": 8,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561197999477537
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 6,
                  "id": "CARD.CAPACITOR"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.LIGHTNING_ROD"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.ENERGY_SURGE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 6,
                "id": "CARD.CAPACITOR"
              }
            ],
            "current_gold": 155,
            "current_hp": 34,
            "damage_taken": 6,
            "gold_gained": 15,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198005465391
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.VINE_SHAMBLER_NORMAL",
            "monster_ids": [
              "MONSTER.VINE_SHAMBLER"
            ],
            "room_type": "monster",
            "turns_taken": 4
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "cards_gained": [
              {
                "id": "CARD.LEAP"
              },
              {
                "id": "CARD.COOLHEADED"
              }
            ],
            "current_gold": 44,
            "current_hp": 32,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "ROOM_FULL_OF_CHEESE.pages.INITIAL.options.GORGE.title",
                  "table": "events"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198218717931
          },
          {
            "cards_gained": [
              {
                "id": "CARD.BOOST_AWAY"
              },
              {
                "id": "CARD.COOLHEADED"
              }
            ],
            "current_gold": 138,
            "current_hp": 36,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "ROOM_FULL_OF_CHEESE.pages.INITIAL.options.GORGE.title",
                  "table": "events"
                },
                "variables": {}
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561197999477537
          },
          {
            "cards_gained": [
              {
                "id": "CARD.BALL_LIGHTNING"
              },
              {
                "id": "CARD.HOLOGRAM"
              }
            ],
            "current_gold": 155,
            "current_hp": 34,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "ROOM_FULL_OF_CHEESE.pages.INITIAL.options.GORGE.title",
                  "table": "events"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198005465391
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.ROOM_FULL_OF_CHEESE",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 44,
            "current_hp": 32,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198218717931,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.BEAM_CELL"
            ]
          },
          {
            "current_gold": 138,
            "current_hp": 36,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561197999477537,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.LOOP"
            ]
          },
          {
            "current_gold": 155,
            "current_hp": 34,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198005465391,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.ECHO_FORM"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "treasure",
        "player_stats": [
          {
            "current_gold": 77,
            "current_hp": 32,
            "damage_taken": 0,
            "gold_gained": 33,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198218717931,
            "relic_choices": [
              {
                "choice": "RELIC.BAG_OF_PREPARATION",
                "was_picked": true
              }
            ]
          },
          {
            "current_gold": 169,
            "current_hp": 36,
            "damage_taken": 0,
            "gold_gained": 31,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561197999477537,
            "relic_choices": [
              {
                "choice": "RELIC.STURDY_CLAMP",
                "was_picked": true
              }
            ]
          },
          {
            "current_gold": 186,
            "current_hp": 34,
            "damage_taken": 0,
            "gold_gained": 31,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198005465391,
            "relic_choices": [
              {
                "choice": "RELIC.PENDULUM",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "treasure",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "elite",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 10,
                  "id": "CARD.COOLHEADED"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.MOMENTUM_STRIKE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.BOOST_AWAY"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 10,
                "id": "CARD.COOLHEADED"
              }
            ],
            "current_gold": 108,
            "current_hp": 19,
            "damage_taken": 13,
            "gold_gained": 31,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198218717931,
            "relic_choices": [
              {
                "choice": "RELIC.BAG_OF_MARBLES",
                "was_picked": true
              }
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 10,
                  "id": "CARD.FIGHT_THROUGH"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.BEAM_CELL"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.SYNTHESIS"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.FIGHT_THROUGH"
              }
            ],
            "current_gold": 199,
            "current_hp": 36,
            "damage_taken": 0,
            "gold_gained": 30,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561197999477537,
            "potion_choices": [
              {
                "choice": "POTION.SPEED_POTION",
                "was_picked": true
              }
            ],
            "potion_used": [
              "POTION.RADIANT_TINCTURE"
            ],
            "relic_choices": [
              {
                "choice": "RELIC.MERCURY_HOURGLASS",
                "was_picked": true
              }
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 10,
                  "id": "CARD.NULL"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.GO_FOR_THE_EYES"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.BARRAGE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 10,
                "id": "CARD.NULL"
              }
            ],
            "current_gold": 215,
            "current_hp": 16,
            "damage_taken": 18,
            "gold_gained": 29,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198005465391,
            "relic_choices": [
              {
                "choice": "RELIC.TUNING_FORK",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.BYGONE_EFFIGY_ELITE",
            "monster_ids": [
              "MONSTER.BYGONE_EFFIGY"
            ],
            "room_type": "elite",
            "turns_taken": 4
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 11,
                  "id": "CARD.BALL_LIGHTNING"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.FOCUSED_STRIKE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.BEAM_CELL"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 11,
                "id": "CARD.BALL_LIGHTNING"
              }
            ],
            "current_gold": 117,
            "current_hp": 9,
            "damage_taken": 10,
            "gold_gained": 9,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198218717931,
            "potion_choices": [
              {
                "choice": "POTION.SPEED_POTION",
                "was_picked": true
              }
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 11,
                  "id": "CARD.BOOST_AWAY"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.BARRAGE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.UPROAR"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.BOOST_AWAY"
              }
            ],
            "current_gold": 210,
            "current_hp": 36,
            "damage_taken": 0,
            "gold_gained": 11,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561197999477537
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 11,
                  "id": "CARD.SUBROUTINE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.GO_FOR_THE_EYES"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.ITERATION"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 11,
                "id": "CARD.SUBROUTINE"
              }
            ],
            "current_gold": 230,
            "current_hp": 4,
            "damage_taken": 12,
            "gold_gained": 15,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198005465391,
            "potion_choices": [
              {
                "choice": "POTION.EXPLOSIVE_AMPOULE",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.SLITHERING_STRANGLER_NORMAL",
            "monster_ids": [
              "MONSTER.TWIG_SLIME_S",
              "MONSTER.TWIG_SLIME_S",
              "MONSTER.SLITHERING_STRANGLER"
            ],
            "room_type": "monster",
            "turns_taken": 3
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 117,
            "current_hp": 31,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 22,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198218717931,
            "rest_site_choices": [
              "HEAL"
            ]
          },
          {
            "current_gold": 210,
            "current_hp": 36,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561197999477537,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.COOLHEADED"
            ]
          },
          {
            "current_gold": 230,
            "current_hp": 26,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 22,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198005465391,
            "rest_site_choices": [
              "HEAL"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 13,
                  "id": "CARD.DOUBLE_ENERGY"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.TESLA_COIL"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.CHILL"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 13,
                "id": "CARD.DOUBLE_ENERGY"
              }
            ],
            "current_gold": 125,
            "current_hp": 30,
            "damage_taken": 1,
            "gold_gained": 8,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198218717931,
            "potion_used": [
              "POTION.SPEED_POTION"
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 13,
                  "id": "CARD.TURBO"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.FUSION"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.OVERCLOCK"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.TURBO"
              }
            ],
            "current_gold": 224,
            "current_hp": 36,
            "damage_taken": 0,
            "gold_gained": 14,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561197999477537,
            "potion_choices": [
              {
                "choice": "POTION.SWIFT_POTION",
                "was_picked": false
              }
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 13,
                  "id": "CARD.BULK_UP"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.WHITE_NOISE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.CLAW"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 13,
                "id": "CARD.BULK_UP"
              }
            ],
            "current_gold": 239,
            "current_hp": 12,
            "damage_taken": 14,
            "gold_gained": 9,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198005465391,
            "potion_choices": [
              {
                "choice": "POTION.TOUCH_OF_INSANITY",
                "was_picked": true
              }
            ],
            "potion_used": [
              "POTION.EXPLOSIVE_AMPOULE"
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.INKLETS_NORMAL",
            "monster_ids": [
              "MONSTER.INKLET",
              "MONSTER.INKLET",
              "MONSTER.INKLET"
            ],
            "room_type": "monster",
            "turns_taken": 4
          }
        ]
      },
      {
        "map_point_type": "elite",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 14,
                  "id": "CARD.LOOP"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.HOLOGRAM"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.COLD_SNAP"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 14,
                "id": "CARD.LOOP"
              }
            ],
            "current_gold": 155,
            "current_hp": 30,
            "damage_taken": 7,
            "gold_gained": 30,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 7,
            "max_hp": 82,
            "max_hp_gained": 7,
            "max_hp_lost": 0,
            "player_id": 76561198218717931,
            "potion_choices": [
              {
                "choice": "POTION.WEAK_POTION",
                "was_picked": true
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.STRAWBERRY",
                "was_picked": true
              }
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 14,
                  "id": "CARD.ROCKET_PUNCH"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.WHITE_NOISE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.SPINNER"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.ROCKET_PUNCH"
              }
            ],
            "current_gold": 255,
            "current_hp": 36,
            "damage_taken": 0,
            "gold_gained": 31,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561197999477537,
            "potion_used": [
              "POTION.POWER_POTION"
            ],
            "relic_choices": [
              {
                "choice": "RELIC.KUNAI",
                "was_picked": true
              }
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 14,
                  "id": "CARD.METEOR_STRIKE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.BARRAGE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.CHARGE_BATTERY"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 14,
                "id": "CARD.METEOR_STRIKE"
              }
            ],
            "current_gold": 271,
            "current_hp": 5,
            "damage_taken": 7,
            "gold_gained": 32,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198005465391,
            "potion_choices": [
              {
                "choice": "POTION.LIQUID_BRONZE",
                "was_picked": false
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.ANCHOR",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.PHROG_PARASITE_ELITE",
            "monster_ids": [
              "MONSTER.PHROG_PARASITE"
            ],
            "room_type": "elite",
            "turns_taken": 6
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 155,
            "current_hp": 30,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 82,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198218717931,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.LOOP"
            ]
          },
          {
            "current_gold": 255,
            "current_hp": 36,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561197999477537,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.COMPACT"
            ]
          },
          {
            "current_gold": 271,
            "current_hp": 27,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 22,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198005465391,
            "rest_site_choices": [
              "HEAL"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "boss",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 16,
                  "id": "CARD.CREATIVE_AI"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.DEFRAGMENT"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.REBOOT"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 16,
                "id": "CARD.CREATIVE_AI"
              }
            ],
            "current_gold": 230,
            "current_hp": 10,
            "damage_taken": 20,
            "gold_gained": 75,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 82,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198218717931,
            "potion_choices": [
              {
                "choice": "POTION.BOTTLED_POTENTIAL",
                "was_picked": true
              }
            ],
            "potion_used": [
              "POTION.COLORLESS_POTION",
              "POTION.WEAK_POTION"
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 16,
                  "id": "CARD.TRASH_TO_TREASURE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.METEOR_STRIKE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.IGNITION"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.TRASH_TO_TREASURE"
              }
            ],
            "current_gold": 330,
            "current_hp": 35,
            "damage_taken": 1,
            "gold_gained": 75,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561197999477537
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 16,
                  "id": "CARD.METEOR_STRIKE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.GENETIC_ALGORITHM",
                  "props": {
                    "ints": [
                      {
                        "name": "CurrentBlock",
                        "value": 1
                      },
                      {
                        "name": "IncreasedBlock",
                        "value": 0
                      }
                    ]
                  }
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.COOLANT"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 16,
                "id": "CARD.METEOR_STRIKE"
              }
            ],
            "current_gold": 346,
            "current_hp": 12,
            "damage_taken": 15,
            "gold_gained": 75,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198005465391,
            "potion_used": [
              "POTION.TOUCH_OF_INSANITY",
              "POTION.DEXTERITY_POTION"
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.VANTOM_BOSS",
            "monster_ids": [
              "MONSTER.VANTOM"
            ],
            "room_type": "boss",
            "turns_taken": 8
          }
        ]
      }
    ],
    [
      {
        "map_point_type": "ancient",
        "player_stats": [
          {
            "ancient_choice": [
              {
                "TextKey": "PAELS_TEARS",
                "title": {
                  "key": "PAELS_TEARS.title",
                  "table": "relics"
                },
                "was_chosen": true
              },
              {
                "TextKey": "PAELS_CLAW",
                "title": {
                  "key": "PAELS_CLAW.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "PAELS_EYE",
                "title": {
                  "key": "PAELS_EYE.title",
                  "table": "relics"
                },
                "was_chosen": false
              }
            ],
            "current_gold": 230,
            "current_hp": 67,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "PAELS_TEARS.title",
                  "table": "relics"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 57,
            "max_hp": 82,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198218717931,
            "relic_choices": [
              {
                "choice": "RELIC.PAELS_TEARS",
                "was_picked": true
              }
            ]
          },
          {
            "ancient_choice": [
              {
                "TextKey": "PAELS_FLESH",
                "title": {
                  "key": "PAELS_FLESH.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "PAELS_GROWTH",
                "title": {
                  "key": "PAELS_GROWTH.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "PAELS_LEGION",
                "title": {
                  "key": "PAELS_LEGION.title",
                  "table": "relics"
                },
                "was_chosen": true
              }
            ],
            "current_gold": 330,
            "current_hp": 67,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "PAELS_LEGION.title",
                  "table": "relics"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 32,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561197999477537,
            "relic_choices": [
              {
                "choice": "RELIC.PAELS_LEGION",
                "was_picked": true
              }
            ]
          },
          {
            "ancient_choice": [
              {
                "TextKey": "PAELS_HORN",
                "title": {
                  "key": "PAELS_HORN.title",
                  "table": "relics"
                },
                "was_chosen": true
              },
              {
                "TextKey": "PAELS_TOOTH",
                "title": {
                  "key": "PAELS_TOOTH.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "PAELS_LEGION",
                "title": {
                  "key": "PAELS_LEGION.title",
                  "table": "relics"
                },
                "was_chosen": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.RELAX"
              },
              {
                "id": "CARD.RELAX"
              }
            ],
            "current_gold": 346,
            "current_hp": 62,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "PAELS_HORN.title",
                  "table": "relics"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 50,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198005465391,
            "relic_choices": [
              {
                "choice": "RELIC.PAELS_HORN",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.PAEL",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 18,
                  "id": "CARD.SYNTHESIS"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.BEAM_CELL"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.BOOST_AWAY"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 18,
                "id": "CARD.SYNTHESIS"
              }
            ],
            "current_gold": 245,
            "current_hp": 51,
            "damage_taken": 16,
            "gold_gained": 15,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 82,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198218717931,
            "potion_choices": [
              {
                "choice": "POTION.ATTACK_POTION",
                "was_picked": true
              }
            ],
            "potion_used": [
              "POTION.BOTTLED_POTENTIAL"
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 18,
                  "id": "CARD.BOOT_SEQUENCE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.HAILSTORM"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.SWEEPING_BEAM"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.BOOT_SEQUENCE"
              }
            ],
            "current_gold": 340,
            "current_hp": 53,
            "damage_taken": 14,
            "gold_gained": 10,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561197999477537
          },
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.GO_FOR_THE_EYES"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.CHARGE_BATTERY"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.CLAW"
                },
                "was_picked": false
              }
            ],
            "current_gold": 353,
            "current_hp": 62,
            "damage_taken": 0,
            "gold_gained": 7,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198005465391,
            "potion_choices": [
              {
                "choice": "POTION.SWIFT_POTION",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.EXOSKELETONS_WEAK",
            "monster_ids": [
              "MONSTER.EXOSKELETON",
              "MONSTER.EXOSKELETON",
              "MONSTER.EXOSKELETON"
            ],
            "room_type": "monster",
            "turns_taken": 5
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 19,
                  "id": "CARD.COOLHEADED"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.HOTFIX"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.THUNDER"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 19,
                "id": "CARD.COOLHEADED"
              }
            ],
            "current_gold": 254,
            "current_hp": 25,
            "damage_taken": 26,
            "gold_gained": 9,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 82,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198218717931,
            "potion_choices": [
              {
                "choice": "POTION.STRENGTH_POTION",
                "was_picked": true
              }
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "floor_added_to_deck": 19,
                  "id": "CARD.ROCKET_PUNCH"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.COLD_SNAP"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.THUNDER"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "current_upgrade_level": 1,
                "id": "CARD.ROCKET_PUNCH"
              }
            ],
            "current_gold": 355,
            "current_hp": 53,
            "damage_taken": 0,
            "gold_gained": 15,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561197999477537,
            "potion_choices": [
              {
                "choice": "POTION.BLESSING_OF_THE_FORGE",
                "was_picked": true
              }
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.TESLA_COIL"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.FOCUSED_STRIKE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.HOTFIX"
                },
                "was_picked": false
              }
            ],
            "current_gold": 362,
            "current_hp": 58,
            "damage_taken": 4,
            "gold_gained": 9,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198005465391
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.BOWLBUGS_WEAK",
            "monster_ids": [
              "MONSTER.BOWLBUG_ROCK",
              "MONSTER.BOWLBUG_NECTAR"
            ],
            "room_type": "monster",
            "turns_taken": 4
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "current_gold": 254,
            "current_hp": 25,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "RANWID_THE_ELDER.pages.INITIAL.options.POTION.title",
                  "table": "events"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 82,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198218717931,
            "potion_discarded": [
              "POTION.ATTACK_POTION"
            ],
            "relic_choices": [
              {
                "choice": "RELIC.STONE_CALENDAR",
                "was_picked": true
              }
            ]
          },
          {
            "current_gold": 355,
            "current_hp": 53,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "RANWID_THE_ELDER.pages.INITIAL.options.POTION.title",
                  "table": "events"
                },
                "variables": {
                  "Potion": {
                    "type": "DynamicString",
                    "decimal_value": 0,
                    "bool_value": false,
                    "string_value": "Speed Potion"
                  },
                  "Relic": {
                    "type": "DynamicString",
                    "decimal_value": 0,
                    "bool_value": false,
                    "string_value": "Sturdy Clamp"
                  }
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561197999477537,
            "potion_discarded": [
              "POTION.SPEED_POTION"
            ],
            "relic_choices": [
              {
                "choice": "RELIC.POTION_BELT",
                "was_picked": true
              }
            ]
          },
          {
            "current_gold": 362,
            "current_hp": 58,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "RANWID_THE_ELDER.pages.INITIAL.options.POTION.title",
                  "table": "events"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198005465391,
            "potion_discarded": [
              "POTION.SWIFT_POTION"
            ],
            "relic_choices": [
              {
                "choice": "RELIC.ODDLY_SMOOTH_STONE",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.RANWID_THE_ELDER",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 21,
                  "id": "CARD.WHITE_NOISE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.CHAOS"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.TURBO"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 21,
                "id": "CARD.WHITE_NOISE"
              }
            ],
            "current_gold": 266,
            "current_hp": 1,
            "damage_taken": 25,
            "gold_gained": 12,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 1,
            "max_hp": 82,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198218717931
          },
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.MOMENTUM_STRIKE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.COOLHEADED"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.BARRAGE"
                },
                "was_picked": false
              }
            ],
            "current_gold": 369,
            "current_hp": 39,
            "damage_taken": 14,
            "gold_gained": 14,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561197999477537,
            "potion_choices": [
              {
                "choice": "POTION.DEXTERITY_POTION",
                "was_picked": true
              }
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "floor_added_to_deck": 21,
                  "id": "CARD.WHITE_NOISE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.SCAVENGE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.CLAW"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "current_upgrade_level": 1,
                "floor_added_to_deck": 21,
                "id": "CARD.WHITE_NOISE"
              }
            ],
            "current_gold": 369,
            "current_hp": 16,
            "damage_taken": 42,
            "gold_gained": 7,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198005465391
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.TUNNELER_NORMAL",
            "monster_ids": [
              "MONSTER.CHOMPER",
              "MONSTER.TUNNELER"
            ],
            "room_type": "monster",
            "turns_taken": 12
          }
        ]
      },
      {
        "map_point_type": "shop",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 22,
                  "id": "CARD.WHITE_NOISE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "floor_added_to_deck": 22,
                  "id": "CARD.HOLOGRAM"
                },
                "was_picked": true
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 22,
                "id": "CARD.WHITE_NOISE"
              },
              {
                "floor_added_to_deck": 22,
                "id": "CARD.HOLOGRAM"
              }
            ],
            "current_gold": 113,
            "current_hp": 1,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 153,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 82,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198218717931,
            "potion_choices": [
              {
                "choice": "POTION.VULNERABLE_POTION",
                "was_picked": true
              }
            ]
          },
          {
            "bought_potions": [
              "POTION.FOCUS_POTION",
              "POTION.BLOCK_POTION"
            ],
            "bought_relics": [
              "RELIC.HORN_CLEAT"
            ],
            "card_choices": [
              {
                "card": {
                  "id": "CARD.TESLA_COIL"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.NULL"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.LEAP"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.BOOST_AWAY"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.HAILSTORM"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.THINKING_AHEAD"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.HAND_OF_GREED"
                },
                "was_picked": false
              }
            ],
            "current_gold": 32,
            "current_hp": 39,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 337,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561197999477537,
            "potion_choices": [
              {
                "choice": "POTION.FOCUS_POTION",
                "was_picked": true
              },
              {
                "choice": "POTION.BLOCK_POTION",
                "was_picked": true
              },
              {
                "choice": "POTION.EXPLOSIVE_AMPOULE",
                "was_picked": false
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.HORN_CLEAT",
                "was_picked": true
              },
              {
                "choice": "RELIC.RED_MASK",
                "was_picked": false
              },
              {
                "choice": "RELIC.PUNCH_DAGGER",
                "was_picked": false
              }
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 22,
                  "id": "CARD.ITERATION"
                },
                "was_picked": true
              },
              {
                "card": {
                  "floor_added_to_deck": 22,
                  "id": "CARD.OVERCLOCK"
                },
                "was_picked": true
              },
              {
                "card": {
                  "floor_added_to_deck": 22,
                  "id": "CARD.TURBO"
                },
                "was_picked": true
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 22,
                "id": "CARD.ITERATION"
              },
              {
                "floor_added_to_deck": 22,
                "id": "CARD.OVERCLOCK"
              },
              {
                "floor_added_to_deck": 22,
                "id": "CARD.TURBO"
              }
            ],
            "cards_removed": [
              {
                "floor_added_to_deck": 1,
                "id": "CARD.STRIKE_DEFECT"
              }
            ],
            "current_gold": 33,
            "current_hp": 16,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 236,
            "gold_spent": 100,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198005465391,
            "potion_choices": [
              {
                "choice": "POTION.CURE_ALL",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "shop",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "elite",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "floor_added_to_deck": 23,
                  "id": "CARD.DARKNESS"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.CHARGE_BATTERY"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.MOMENTUM_STRIKE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "current_upgrade_level": 1,
                "floor_added_to_deck": 23,
                "id": "CARD.DARKNESS"
              }
            ],
            "current_gold": 142,
            "current_hp": 1,
            "damage_taken": 1,
            "gold_gained": 29,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 1,
            "max_hp": 82,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198218717931,
            "potion_choices": [
              {
                "choice": "POTION.LIQUID_BRONZE",
                "was_picked": true
              }
            ],
            "potion_used": [
              "POTION.STRENGTH_POTION",
              "POTION.VULNERABLE_POTION"
            ],
            "relic_choices": [
              {
                "choice": "RELIC.SHOVEL",
                "was_picked": true
              }
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 23,
                  "id": "CARD.MACHINE_LEARNING"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.GLASSWORK"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.LOOP"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.MACHINE_LEARNING"
              }
            ],
            "current_gold": 59,
            "current_hp": 30,
            "damage_taken": 9,
            "gold_gained": 27,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561197999477537,
            "potion_used": [
              "POTION.FOCUS_POTION",
              "POTION.BLOCK_POTION",
              "POTION.BLESSING_OF_THE_FORGE"
            ],
            "relic_choices": [
              {
                "choice": "RELIC.SHURIKEN",
                "was_picked": true
              }
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.SCAVENGE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.SUNDER"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.CHAOS"
                },
                "was_picked": false
              }
            ],
            "current_gold": 60,
            "current_hp": 1,
            "damage_taken": 16,
            "gold_gained": 27,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 1,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198005465391,
            "potion_choices": [
              {
                "choice": "POTION.POWDERED_DEMISE",
                "was_picked": true
              }
            ],
            "potion_used": [
              "POTION.CURE_ALL"
            ],
            "relic_choices": [
              {
                "choice": "RELIC.CENTENNIAL_PUZZLE",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.DECIMILLIPEDE_ELITE",
            "monster_ids": [
              "MONSTER.DECIMILLIPEDE_SEGMENT_FRONT",
              "MONSTER.DECIMILLIPEDE_SEGMENT_MIDDLE",
              "MONSTER.DECIMILLIPEDE_SEGMENT_BACK"
            ],
            "room_type": "elite",
            "turns_taken": 18
          }
        ]
      },
      {
        "map_point_type": "treasure",
        "player_stats": [
          {
            "current_gold": 179,
            "current_hp": 1,
            "damage_taken": 0,
            "gold_gained": 37,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 82,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198218717931,
            "relic_choices": [
              {
                "choice": "RELIC.STRIKE_DUMMY",
                "was_picked": true
              }
            ]
          },
          {
            "current_gold": 92,
            "current_hp": 30,
            "damage_taken": 0,
            "gold_gained": 33,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561197999477537,
            "relic_choices": [
              {
                "choice": "RELIC.PETRIFIED_TOAD",
                "was_picked": true
              }
            ]
          },
          {
            "current_gold": 92,
            "current_hp": 1,
            "damage_taken": 0,
            "gold_gained": 32,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198005465391,
            "relic_choices": [
              {
                "choice": "RELIC.VENERABLE_TEA_SET",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "treasure",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 179,
            "current_hp": 1,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 82,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198218717931,
            "relic_choices": [
              {
                "choice": "RELIC.MINIATURE_CANNON",
                "was_picked": true
              }
            ],
            "rest_site_choices": [
              "DIG"
            ]
          },
          {
            "current_gold": 92,
            "current_hp": 30,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561197999477537,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.TRASH_TO_TREASURE"
            ]
          },
          {
            "current_gold": 92,
            "current_hp": 23,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 22,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198005465391,
            "rest_site_choices": [
              "HEAL"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "cards_removed": [
              {
                "floor_added_to_deck": 5,
                "id": "CARD.HOLOGRAM"
              }
            ],
            "current_gold": 179,
            "current_hp": 1,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "SLIPPERY_BRIDGE.pages.INITIAL.options.OVERCOME.title",
                  "table": "events"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 82,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198218717931
          },
          {
            "cards_removed": [
              {
                "floor_added_to_deck": 1,
                "id": "CARD.LEAP"
              }
            ],
            "current_gold": 92,
            "current_hp": 30,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "SLIPPERY_BRIDGE.pages.INITIAL.options.OVERCOME.title",
                  "table": "events"
                },
                "variables": {
                  "RandomCard": {
                    "type": "DynamicString",
                    "decimal_value": 0,
                    "bool_value": false,
                    "string_value": "Leap"
                  },
                  "HpLoss": {
                    "type": "BaseDynamic",
                    "decimal_value": 3,
                    "bool_value": false,
                    "string_value": null
                  }
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561197999477537
          },
          {
            "cards_removed": [
              {
                "floor_added_to_deck": 11,
                "id": "CARD.SUBROUTINE"
              }
            ],
            "current_gold": 92,
            "current_hp": 16,
            "damage_taken": 7,
            "event_choices": [
              {
                "title": {
                  "key": "SLIPPERY_BRIDGE.pages.INITIAL.options.HOLD_ON_0.title",
                  "table": "events"
                }
              },
              {
                "title": {
                  "key": "SLIPPERY_BRIDGE.pages.HOLD_ON_0.options.HOLD_ON_1.title",
                  "table": "events"
                }
              },
              {
                "title": {
                  "key": "SLIPPERY_BRIDGE.pages.INITIAL.options.OVERCOME.title",
                  "table": "events"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198005465391
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.SLIPPERY_BRIDGE",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 179,
            "current_hp": 25,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 24,
            "max_hp": 82,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198218717931,
            "relic_choices": [
              {
                "choice": "RELIC.TUNING_FORK",
                "was_picked": true
              }
            ],
            "rest_site_choices": [
              "DIG"
            ]
          },
          {
            "current_gold": 92,
            "current_hp": 30,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561197999477537,
            "rest_site_choices": [
              "MEND"
            ]
          },
          {
            "current_gold": 92,
            "current_hp": 38,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 22,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198005465391,
            "rest_site_choices": [
              "HEAL"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "elite",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 28,
                  "id": "CARD.SHADOW_SHIELD"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.GUNK_UP"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.COLD_SNAP"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 28,
                "id": "CARD.SHADOW_SHIELD"
              }
            ],
            "current_gold": 211,
            "current_hp": 1,
            "damage_taken": 25,
            "gold_gained": 32,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 1,
            "max_hp": 82,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198218717931,
            "potion_used": [
              "POTION.LIQUID_BRONZE"
            ],
            "relic_choices": [
              {
                "choice": "RELIC.ANCHOR",
                "was_picked": true
              }
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "floor_added_to_deck": 28,
                  "id": "CARD.COMPILE_DRIVER"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.CHARGE_BATTERY"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.HOTFIX"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "current_upgrade_level": 1,
                "id": "CARD.COMPILE_DRIVER"
              }
            ],
            "current_gold": 124,
            "current_hp": 30,
            "damage_taken": 0,
            "gold_gained": 32,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561197999477537,
            "potion_choices": [
              {
                "choice": "POTION.POTION_SHAPED_ROCK",
                "was_picked": true
              },
              {
                "choice": "POTION.COLORLESS_POTION",
                "was_picked": true
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.VAJRA",
                "was_picked": true
              }
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 28,
                  "id": "CARD.FIGHT_THROUGH"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.DOUBLE_ENERGY"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.MODDED"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 28,
                "id": "CARD.FIGHT_THROUGH"
              }
            ],
            "current_gold": 120,
            "current_hp": 1,
            "damage_taken": 38,
            "gold_gained": 28,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 1,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198005465391,
            "potion_choices": [
              {
                "choice": "POTION.FLEX_POTION",
                "was_picked": true
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.PLANISPHERE",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.INFESTED_PRISMS_ELITE",
            "monster_ids": [
              "MONSTER.INFESTED_PRISM"
            ],
            "room_type": "elite",
            "turns_taken": 12
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 29,
                  "id": "CARD.SKIM"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.SWEEPING_BEAM"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.COMPILE_DRIVER"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 29,
                "id": "CARD.SKIM"
              }
            ],
            "current_gold": 224,
            "current_hp": 1,
            "damage_taken": 1,
            "gold_gained": 13,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 1,
            "max_hp": 82,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198218717931
          },
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.BULK_UP"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.BEAM_CELL"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.FERAL"
                },
                "was_picked": false
              }
            ],
            "current_gold": 133,
            "current_hp": 30,
            "damage_taken": 0,
            "gold_gained": 9,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561197999477537,
            "potion_choices": [
              {
                "choice": "POTION.POTION_SHAPED_ROCK",
                "was_picked": true
              },
              {
                "choice": "POTION.POWER_POTION",
                "was_picked": true
              }
            ],
            "potion_used": [
              "POTION.POTION_SHAPED_ROCK",
              "POTION.COLORLESS_POTION",
              "POTION.POTION_SHAPED_ROCK"
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "floor_added_to_deck": 29,
                  "id": "CARD.BOOST_AWAY"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.ITERATION"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.GUNK_UP"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "current_upgrade_level": 1,
                "floor_added_to_deck": 29,
                "id": "CARD.BOOST_AWAY"
              }
            ],
            "current_gold": 134,
            "current_hp": 1,
            "damage_taken": 1,
            "gold_gained": 14,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 1,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198005465391,
            "potion_choices": [
              {
                "choice": "POTION.FIRE_POTION",
                "was_picked": true
              }
            ],
            "potion_used": [
              "POTION.FLEX_POTION"
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.THE_OBSCURA_NORMAL",
            "monster_ids": [
              "MONSTER.THE_OBSCURA"
            ],
            "room_type": "monster",
            "turns_taken": 12
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 224,
            "current_hp": 25,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 24,
            "max_hp": 82,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198218717931,
            "relic_choices": [
              {
                "choice": "RELIC.VAJRA",
                "was_picked": true
              }
            ],
            "rest_site_choices": [
              "DIG"
            ]
          },
          {
            "current_gold": 133,
            "current_hp": 30,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561197999477537,
            "rest_site_choices": [
              "MEND"
            ]
          },
          {
            "current_gold": 134,
            "current_hp": 23,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 22,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198005465391,
            "rest_site_choices": [
              "HEAL"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "boss",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 31,
                  "id": "CARD.MODDED"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.ALL_FOR_ONE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.SUPERCRITICAL"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 31,
                "id": "CARD.MODDED"
              }
            ],
            "current_gold": 299,
            "current_hp": 1,
            "damage_taken": 25,
            "gold_gained": 75,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 1,
            "max_hp": 82,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198218717931
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 31,
                  "id": "CARD.SIGNAL_BOOST"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.REBOOT"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.GENETIC_ALGORITHM",
                  "props": {
                    "ints": [
                      {
                        "name": "CurrentBlock",
                        "value": 1
                      },
                      {
                        "name": "IncreasedBlock",
                        "value": 0
                      }
                    ]
                  }
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.SIGNAL_BOOST"
              }
            ],
            "current_gold": 208,
            "current_hp": 30,
            "damage_taken": 0,
            "gold_gained": 75,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561197999477537,
            "potion_choices": [
              {
                "choice": "POTION.POTION_SHAPED_ROCK",
                "was_picked": true
              },
              {
                "choice": "POTION.SKILL_POTION",
                "was_picked": true
              }
            ],
            "potion_used": [
              "POTION.POWER_POTION",
              "POTION.DEXTERITY_POTION"
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 31,
                  "id": "CARD.DEFRAGMENT"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.ADAPTIVE_STRIKE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.HELIX_DRILL"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 31,
                "id": "CARD.DEFRAGMENT"
              }
            ],
            "current_gold": 209,
            "current_hp": 1,
            "damage_taken": 23,
            "gold_gained": 75,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 1,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198005465391,
            "potion_choices": [
              {
                "choice": "POTION.GAMBLERS_BREW",
                "was_picked": true
              }
            ],
            "potion_used": [
              "POTION.FIRE_POTION"
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.KAISER_CRAB_BOSS",
            "monster_ids": [
              "MONSTER.CRUSHER",
              "MONSTER.ROCKET"
            ],
            "room_type": "boss",
            "turns_taken": 17
          }
        ]
      }
    ],
    [
      {
        "map_point_type": "ancient",
        "player_stats": [
          {
            "ancient_choice": [
              {
                "TextKey": "CROSSBOW",
                "title": {
                  "key": "CROSSBOW.title",
                  "table": "relics"
                },
                "was_chosen": true
              },
              {
                "TextKey": "THROWING_AXE",
                "title": {
                  "key": "THROWING_AXE.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "SAI",
                "title": {
                  "key": "SAI.title",
                  "table": "relics"
                },
                "was_chosen": false
              }
            ],
            "current_gold": 299,
            "current_hp": 65,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "CROSSBOW.title",
                  "table": "relics"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 64,
            "max_hp": 82,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198218717931,
            "relic_choices": [
              {
                "choice": "RELIC.CROSSBOW",
                "was_picked": true
              }
            ]
          },
          {
            "ancient_choice": [
              {
                "TextKey": "CROSSBOW",
                "title": {
                  "key": "CROSSBOW.title",
                  "table": "relics"
                },
                "was_chosen": true
              },
              {
                "TextKey": "WAR_HAMMER",
                "title": {
                  "key": "WAR_HAMMER.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "TANXS_WHISTLE",
                "title": {
                  "key": "TANXS_WHISTLE.title",
                  "table": "relics"
                },
                "was_chosen": false
              }
            ],
            "current_gold": 208,
            "current_hp": 66,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "CROSSBOW.title",
                  "table": "relics"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 36,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561197999477537,
            "relic_choices": [
              {
                "choice": "RELIC.CROSSBOW",
                "was_picked": true
              }
            ]
          },
          {
            "ancient_choice": [
              {
                "TextKey": "SAI",
                "title": {
                  "key": "SAI.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "CROSSBOW",
                "title": {
                  "key": "CROSSBOW.title",
                  "table": "relics"
                },
                "was_chosen": true
              },
              {
                "TextKey": "TRI_BOOMERANG",
                "title": {
                  "key": "TRI_BOOMERANG.title",
                  "table": "relics"
                },
                "was_chosen": false
              }
            ],
            "current_gold": 209,
            "current_hp": 60,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "CROSSBOW.title",
                  "table": "relics"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 59,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198005465391,
            "relic_choices": [
              {
                "choice": "RELIC.CROSSBOW",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.TANX",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 33,
                  "id": "CARD.COOLHEADED"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.SHADOW_SHIELD"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.FOCUSED_STRIKE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 33,
                "id": "CARD.COOLHEADED"
              }
            ],
            "current_gold": 306,
            "current_hp": 65,
            "damage_taken": 0,
            "gold_gained": 7,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 82,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198218717931
          },
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.BULK_UP"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.FUSION"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.CHILL"
                },
                "was_picked": false
              }
            ],
            "current_gold": 222,
            "current_hp": 66,
            "damage_taken": 0,
            "gold_gained": 14,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561197999477537,
            "potion_choices": [
              {
                "choice": "POTION.POTION_SHAPED_ROCK",
                "was_picked": true
              }
            ],
            "potion_used": [
              "POTION.POTION_SHAPED_ROCK",
              "POTION.POTION_SHAPED_ROCK"
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 33,
                  "id": "CARD.SYNTHESIS"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.TEMPEST"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.FTL"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 33,
                "id": "CARD.SYNTHESIS"
              }
            ],
            "current_gold": 224,
            "current_hp": 60,
            "damage_taken": 0,
            "gold_gained": 15,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198005465391
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.DEVOTED_SCULPTOR_WEAK",
            "monster_ids": [
              "MONSTER.DEVOTED_SCULPTOR"
            ],
            "room_type": "monster",
            "turns_taken": 3
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "cards_gained": [
              {
                "id": "CARD.MAD_SCIENCE",
                "props": {
                  "ints": [
                    {
                      "name": "TinkerTimeType",
                      "value": 2
                    },
                    {
                      "name": "TinkerTimeRider",
                      "value": 4
                    }
                  ]
                }
              }
            ],
            "current_gold": 306,
            "current_hp": 65,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "TINKER_TIME.pages.INITIAL.options.CHOOSE_CARD_TYPE.title",
                  "table": "events"
                }
              },
              {
                "title": {
                  "key": "TINKER_TIME.pages.CHOOSE_CARD_TYPE.options.SKILL.title",
                  "table": "events"
                }
              },
              {
                "title": {
                  "key": "TINKER_TIME.pages.CHOOSE_RIDER.options.ENERGIZED.title",
                  "table": "events"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 82,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198218717931
          },
          {
            "cards_gained": [
              {
                "id": "CARD.MAD_SCIENCE",
                "props": {
                  "ints": [
                    {
                      "name": "TinkerTimeType",
                      "value": 3
                    },
                    {
                      "name": "TinkerTimeRider",
                      "value": 7
                    }
                  ]
                }
              }
            ],
            "current_gold": 222,
            "current_hp": 66,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "TINKER_TIME.pages.INITIAL.options.CHOOSE_CARD_TYPE.title",
                  "table": "events"
                },
                "variables": {
                  "ViolenceHits": {
                    "type": "BaseDynamic",
                    "decimal_value": 3,
                    "bool_value": false,
                    "string_value": null
                  },
                  "CuriousReduction": {
                    "type": "BaseDynamic",
                    "decimal_value": 1,
                    "bool_value": false,
                    "string_value": null
                  }
                }
              },
              {
                "title": {
                  "key": "TINKER_TIME.pages.CHOOSE_CARD_TYPE.options.POWER.title",
                  "table": "events"
                },
                "variables": {
                  "ViolenceHits": {
                    "type": "BaseDynamic",
                    "decimal_value": 3,
                    "bool_value": false,
                    "string_value": null
                  },
                  "CuriousReduction": {
                    "type": "BaseDynamic",
                    "decimal_value": 1,
                    "bool_value": false,
                    "string_value": null
                  }
                }
              },
              {
                "title": {
                  "key": "TINKER_TIME.pages.CHOOSE_RIDER.options.EXPERTISE.title",
                  "table": "events"
                },
                "variables": {
                  "ViolenceHits": {
                    "type": "BaseDynamic",
                    "decimal_value": 3,
                    "bool_value": false,
                    "string_value": null
                  },
                  "CuriousReduction": {
                    "type": "BaseDynamic",
                    "decimal_value": 1,
                    "bool_value": false,
                    "string_value": null
                  }
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561197999477537
          },
          {
            "cards_gained": [
              {
                "id": "CARD.MAD_SCIENCE",
                "props": {
                  "ints": [
                    {
                      "name": "TinkerTimeType",
                      "value": 2
                    },
                    {
                      "name": "TinkerTimeRider",
                      "value": 5
                    }
                  ]
                }
              }
            ],
            "current_gold": 224,
            "current_hp": 65,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "TINKER_TIME.pages.INITIAL.options.CHOOSE_CARD_TYPE.title",
                  "table": "events"
                }
              },
              {
                "title": {
                  "key": "TINKER_TIME.pages.CHOOSE_CARD_TYPE.options.SKILL.title",
                  "table": "events"
                }
              },
              {
                "title": {
                  "key": "TINKER_TIME.pages.CHOOSE_RIDER.options.WISDOM.title",
                  "table": "events"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 5,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198005465391
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.TINKER_TIME",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "current_gold": 306,
            "current_hp": 65,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "POTION_COURIER.pages.INITIAL.options.RANSACK.title",
                  "table": "events"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 82,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198218717931,
            "potion_choices": [
              {
                "choice": "POTION.GAMBLERS_BREW",
                "was_picked": true
              }
            ]
          },
          {
            "current_gold": 222,
            "current_hp": 66,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "POTION_COURIER.pages.INITIAL.options.GRAB_POTIONS.title",
                  "table": "events"
                },
                "variables": {
                  "FoulPotions": {
                    "type": "BaseDynamic",
                    "decimal_value": 3,
                    "bool_value": false,
                    "string_value": null
                  }
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561197999477537,
            "potion_choices": [
              {
                "choice": "POTION.FOUL_POTION",
                "was_picked": true
              },
              {
                "choice": "POTION.FOUL_POTION",
                "was_picked": true
              },
              {
                "choice": "POTION.FOUL_POTION",
                "was_picked": true
              }
            ]
          },
          {
            "current_gold": 224,
            "current_hp": 70,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "POTION_COURIER.pages.INITIAL.options.RANSACK.title",
                  "table": "events"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 5,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198005465391,
            "potion_choices": [
              {
                "choice": "POTION.POTION_OF_BINDING",
                "was_picked": true
              }
            ],
            "potion_discarded": [
              "POTION.POWDERED_DEMISE"
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.POTION_COURIER",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "current_gold": 338,
            "current_hp": 65,
            "damage_taken": 0,
            "gold_gained": 32,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 82,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198218717931,
            "relic_choices": [
              {
                "choice": "RELIC.ICE_CREAM",
                "was_picked": true
              }
            ]
          },
          {
            "current_gold": 260,
            "current_hp": 66,
            "damage_taken": 0,
            "gold_gained": 38,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561197999477537,
            "relic_choices": [
              {
                "choice": "RELIC.ORICHALCUM",
                "was_picked": true
              }
            ]
          },
          {
            "current_gold": 257,
            "current_hp": 75,
            "damage_taken": 0,
            "gold_gained": 33,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 5,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198005465391,
            "relic_choices": [
              {
                "choice": "RELIC.WAR_PAINT",
                "was_picked": true
              }
            ],
            "upgraded_cards": [
              "CARD.RELAX",
              "CARD.DEFEND_DEFECT"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "treasure",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "cards_gained": [
              {
                "id": "CARD.CLUMSY"
              }
            ],
            "current_gold": 338,
            "current_hp": 65,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "THIS_OR_THAT.pages.INITIAL.options.ORNATE.title",
                  "table": "events"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 82,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198218717931,
            "relic_choices": [
              {
                "choice": "RELIC.RAINBOW_RING",
                "was_picked": true
              }
            ]
          },
          {
            "cards_gained": [
              {
                "id": "CARD.CLUMSY"
              }
            ],
            "current_gold": 260,
            "current_hp": 66,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "THIS_OR_THAT.pages.INITIAL.options.ORNATE.title",
                  "table": "events"
                },
                "variables": {
                  "Curse": {
                    "type": "DynamicString",
                    "decimal_value": 0,
                    "bool_value": false,
                    "string_value": "Clumsy"
                  }
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561197999477537,
            "relic_choices": [
              {
                "choice": "RELIC.HAPPY_FLOWER",
                "was_picked": true
              }
            ]
          },
          {
            "current_gold": 314,
            "current_hp": 69,
            "damage_taken": 6,
            "event_choices": [
              {
                "title": {
                  "key": "THIS_OR_THAT.pages.INITIAL.options.PLAIN.title",
                  "table": "events"
                }
              }
            ],
            "gold_gained": 57,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198005465391
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.THIS_OR_THAT",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "treasure",
        "player_stats": [
          {
            "current_gold": 377,
            "current_hp": 65,
            "damage_taken": 0,
            "gold_gained": 39,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 82,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198218717931,
            "relic_choices": [
              {
                "choice": "RELIC.CHANDELIER",
                "was_picked": true
              }
            ]
          },
          {
            "current_gold": 298,
            "current_hp": 66,
            "damage_taken": 0,
            "gold_gained": 38,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561197999477537,
            "relic_choices": [
              {
                "choice": "RELIC.BLOOD_VIAL",
                "was_picked": true
              }
            ]
          },
          {
            "current_gold": 350,
            "current_hp": 69,
            "damage_taken": 0,
            "gold_gained": 36,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198005465391,
            "relic_choices": [
              {
                "choice": "RELIC.RIPPLE_BASIN",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "treasure",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 377,
            "current_hp": 65,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 82,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198218717931,
            "relic_choices": [
              {
                "choice": "RELIC.LANTERN",
                "was_picked": true
              }
            ],
            "rest_site_choices": [
              "DIG"
            ]
          },
          {
            "current_gold": 298,
            "current_hp": 66,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561197999477537,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.NULL"
            ]
          },
          {
            "current_gold": 350,
            "current_hp": 69,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198005465391,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.MAD_SCIENCE"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 40,
                  "id": "CARD.BOOT_SEQUENCE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.GO_FOR_THE_EYES"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.DOUBLE_ENERGY"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 40,
                "id": "CARD.BOOT_SEQUENCE"
              }
            ],
            "current_gold": 384,
            "current_hp": 65,
            "damage_taken": 0,
            "gold_gained": 7,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 82,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198218717931
          },
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.CHARGE_BATTERY"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.TURBO"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.COLD_SNAP"
                },
                "was_picked": false
              }
            ],
            "current_gold": 310,
            "current_hp": 60,
            "damage_taken": 8,
            "gold_gained": 12,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 2,
            "max_hp": 71,
            "max_hp_gained": 0,
            "max_hp_lost": 4,
            "player_id": 76561197999477537,
            "potion_choices": [
              {
                "choice": "POTION.FOCUS_POTION",
                "was_picked": true
              }
            ],
            "potion_used": [
              "POTION.SKILL_POTION"
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.MOMENTUM_STRIKE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.HOTFIX"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.GO_FOR_THE_EYES"
                },
                "was_picked": false
              }
            ],
            "current_gold": 362,
            "current_hp": 74,
            "damage_taken": 0,
            "gold_gained": 12,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 5,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198005465391,
            "potion_choices": [
              {
                "choice": "POTION.FYSH_OIL",
                "was_picked": false
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.SCROLLS_OF_BITING_WEAK",
            "monster_ids": [
              "MONSTER.SCROLL_OF_BITING",
              "MONSTER.SCROLL_OF_BITING",
              "MONSTER.SCROLL_OF_BITING"
            ],
            "room_type": "monster",
            "turns_taken": 3
          }
        ]
      },
      {
        "map_point_type": "elite",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.BEAM_CELL"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.MOMENTUM_STRIKE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.BARRAGE"
                },
                "was_picked": false
              }
            ],
            "current_gold": 411,
            "current_hp": 60,
            "damage_taken": 5,
            "gold_gained": 27,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 82,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198218717931,
            "potion_choices": [
              {
                "choice": "POTION.BLOCK_POTION",
                "was_picked": true
              }
            ],
            "potion_used": [
              "POTION.GAMBLERS_BREW"
            ],
            "relic_choices": [
              {
                "choice": "RELIC.MERCURY_HOURGLASS",
                "was_picked": true
              }
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "floor_added_to_deck": 41,
                  "id": "CARD.FIGHT_THROUGH"
                },
                "was_picked": true
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.TURBO"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.GLASSWORK"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "current_upgrade_level": 1,
                "id": "CARD.FIGHT_THROUGH"
              }
            ],
            "current_gold": 339,
            "current_hp": 61,
            "damage_taken": 1,
            "gold_gained": 29,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 2,
            "max_hp": 71,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561197999477537,
            "potion_used": [
              "POTION.FOCUS_POTION"
            ],
            "relic_choices": [
              {
                "choice": "RELIC.TUNGSTEN_ROD",
                "was_picked": true
              }
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.BEAM_CELL"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.UPROAR"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.SHADOW_SHIELD"
                },
                "was_picked": false
              }
            ],
            "current_gold": 394,
            "current_hp": 64,
            "damage_taken": 10,
            "gold_gained": 32,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198005465391,
            "potion_choices": [
              {
                "choice": "POTION.HEART_OF_IRON",
                "was_picked": true
              }
            ],
            "potion_used": [
              "POTION.POTION_OF_BINDING",
              "POTION.GAMBLERS_BREW"
            ],
            "relic_choices": [
              {
                "choice": "RELIC.NUNCHAKU",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.KNIGHTS_ELITE",
            "monster_ids": [
              "MONSTER.FLAIL_KNIGHT",
              "MONSTER.SPECTRAL_KNIGHT",
              "MONSTER.MAGI_KNIGHT"
            ],
            "room_type": "elite",
            "turns_taken": 5
          }
        ]
      },
      {
        "map_point_type": "shop",
        "player_stats": [
          {
            "cards_removed": [
              {
                "floor_added_to_deck": 37,
                "id": "CARD.CLUMSY"
              }
            ],
            "current_gold": 52,
            "current_hp": 60,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 259,
            "gold_spent": 100,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 82,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198218717931,
            "potion_choices": [
              {
                "choice": "POTION.ENERGY_POTION",
                "was_picked": true
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.ETERNAL_FEATHER",
                "was_picked": true
              }
            ]
          },
          {
            "bought_colorless": [
              "CARD.DISCOVERY"
            ],
            "bought_potions": [
              "POTION.DUPLICATOR",
              "POTION.FIRE_POTION"
            ],
            "bought_relics": [
              "RELIC.DATA_DISK",
              "RELIC.ODDLY_SMOOTH_STONE"
            ],
            "card_choices": [
              {
                "card": {
                  "id": "CARD.SCRAPE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.MOMENTUM_STRIKE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.LIGHTNING_ROD"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.LEAP"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.HAILSTORM"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.ALCHEMIZE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.DISCOVERY"
              }
            ],
            "current_gold": 31,
            "current_hp": 61,
            "damage_taken": 0,
            "gold_gained": 300,
            "gold_lost": 0,
            "gold_spent": 608,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 71,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561197999477537,
            "potion_choices": [
              {
                "choice": "POTION.DUPLICATOR",
                "was_picked": true
              },
              {
                "choice": "POTION.FIRE_POTION",
                "was_picked": true
              },
              {
                "choice": "POTION.EXPLOSIVE_AMPOULE",
                "was_picked": false
              }
            ],
            "potion_used": [
              "POTION.FOUL_POTION",
              "POTION.FOUL_POTION",
              "POTION.FOUL_POTION"
            ],
            "relic_choices": [
              {
                "choice": "RELIC.DATA_DISK",
                "was_picked": true
              },
              {
                "choice": "RELIC.ODDLY_SMOOTH_STONE",
                "was_picked": true
              },
              {
                "choice": "RELIC.WING_CHARM",
                "was_picked": false
              }
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 42,
                  "id": "CARD.BEACON_OF_HOPE"
                },
                "was_picked": true
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 42,
                "id": "CARD.BEACON_OF_HOPE"
              }
            ],
            "cards_removed": [
              {
                "floor_added_to_deck": 1,
                "id": "CARD.STRIKE_DEFECT"
              }
            ],
            "current_gold": 70,
            "current_hp": 64,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 174,
            "gold_spent": 150,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198005465391
          }
        ],
        "rooms": [
          {
            "room_type": "shop",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "elite",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "floor_added_to_deck": 43,
                  "id": "CARD.SUBROUTINE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.FOCUSED_STRIKE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.FIGHT_THROUGH"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "current_upgrade_level": 1,
                "floor_added_to_deck": 43,
                "id": "CARD.SUBROUTINE"
              }
            ],
            "current_gold": 84,
            "current_hp": 60,
            "damage_taken": 0,
            "gold_gained": 32,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 82,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198218717931,
            "potion_used": [
              "POTION.BLOCK_POTION"
            ],
            "relic_choices": [
              {
                "choice": "RELIC.DATA_DISK",
                "was_picked": true
              }
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.NULL"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.TURBO"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.DARKNESS"
                },
                "was_picked": false
              }
            ],
            "current_gold": 61,
            "current_hp": 63,
            "damage_taken": 0,
            "gold_gained": 30,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 2,
            "max_hp": 71,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561197999477537,
            "potion_choices": [
              {
                "choice": "POTION.POTION_SHAPED_ROCK",
                "was_picked": true
              },
              {
                "choice": "POTION.VULNERABLE_POTION",
                "was_picked": true
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.ORNAMENTAL_FAN",
                "was_picked": true
              }
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 43,
                  "id": "CARD.OVERCLOCK"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.COOLHEADED"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.BALL_LIGHTNING"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 43,
                "id": "CARD.OVERCLOCK"
              }
            ],
            "current_gold": 97,
            "current_hp": 36,
            "damage_taken": 28,
            "gold_gained": 27,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198005465391,
            "potion_choices": [
              {
                "choice": "POTION.GAMBLERS_BREW",
                "was_picked": true
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.RED_MASK",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.SOUL_NEXUS_ELITE",
            "monster_ids": [
              "MONSTER.SOUL_NEXUS"
            ],
            "room_type": "elite",
            "turns_taken": 5
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 84,
            "current_hp": 81,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 21,
            "max_hp": 82,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198218717931,
            "relic_choices": [
              {
                "choice": "RELIC.WHETSTONE",
                "was_picked": true
              }
            ],
            "rest_site_choices": [
              "DIG"
            ],
            "upgraded_cards": [
              "CARD.NULL",
              "CARD.STRIKE_DEFECT"
            ]
          },
          {
            "current_gold": 61,
            "current_hp": 63,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 71,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561197999477537,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.DISCOVERY"
            ]
          },
          {
            "current_gold": 97,
            "current_hp": 58,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 22,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198005465391,
            "rest_site_choices": [
              "HEAL"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "boss",
        "player_stats": [
          {
            "current_gold": 84,
            "current_hp": 58,
            "damage_taken": 23,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 82,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198218717931,
            "potion_used": [
              "POTION.ENERGY_POTION"
            ]
          },
          {
            "current_gold": 61,
            "current_hp": 53,
            "damage_taken": 12,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 2,
            "max_hp": 71,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561197999477537
          },
          {
            "current_gold": 97,
            "current_hp": 46,
            "damage_taken": 12,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198005465391,
            "potion_used": [
              "POTION.GAMBLERS_BREW",
              "POTION.HEART_OF_IRON"
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.TEST_SUBJECT_BOSS",
            "monster_ids": [
              "MONSTER.TEST_SUBJECT"
            ],
            "room_type": "boss",
            "turns_taken": 9
          }
        ]
      },
      {
        "map_point_type": "boss",
        "player_stats": [
          {
            "current_gold": 84,
            "current_hp": 49,
            "damage_taken": 9,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 82,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198218717931
          },
          {
            "current_gold": 61,
            "current_hp": 55,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 2,
            "max_hp": 71,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561197999477537,
            "potion_used": [
              "POTION.POTION_SHAPED_ROCK",
              "POTION.VULNERABLE_POTION",
              "POTION.DUPLICATOR",
              "POTION.FIRE_POTION"
            ]
          },
          {
            "current_gold": 97,
            "current_hp": 18,
            "damage_taken": 28,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198005465391
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.QUEEN_BOSS",
            "monster_ids": [
              "MONSTER.TORCH_HEAD_AMALGAM",
              "MONSTER.QUEEN"
            ],
            "room_type": "boss",
            "turns_taken": 10
          }
        ]
      }
    ]
  ],
  "modifiers": [],
  "platform_type": "steam",
  "players": [
    {
      "badges": [
        {
          "id": "ELITE",
          "rarity": "silver"
        }
      ],
      "character": "CHARACTER.DEFECT",
      "deck": [
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 1,
          "id": "CARD.STRIKE_DEFECT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.STRIKE_DEFECT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.STRIKE_DEFECT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.STRIKE_DEFECT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_DEFECT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_DEFECT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_DEFECT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_DEFECT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.ZAP"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DUALCAST"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.ASCENDERS_BANE"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.BARRAGE"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 1,
          "id": "CARD.BEAM_CELL"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.WHITE_NOISE"
        },
        {
          "floor_added_to_deck": 2,
          "id": "CARD.TURBO"
        },
        {
          "current_upgrade_level": 1,
          "enchantment": {
            "amount": 1,
            "id": "ENCHANTMENT.SLITHER"
          },
          "floor_added_to_deck": 3,
          "id": "CARD.NULL"
        },
        {
          "floor_added_to_deck": 6,
          "id": "CARD.CHARGE_BATTERY"
        },
        {
          "floor_added_to_deck": 7,
          "id": "CARD.LEAP"
        },
        {
          "floor_added_to_deck": 7,
          "id": "CARD.COOLHEADED"
        },
        {
          "floor_added_to_deck": 10,
          "id": "CARD.COOLHEADED"
        },
        {
          "floor_added_to_deck": 11,
          "id": "CARD.BALL_LIGHTNING"
        },
        {
          "floor_added_to_deck": 13,
          "id": "CARD.DOUBLE_ENERGY"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 14,
          "id": "CARD.LOOP"
        },
        {
          "floor_added_to_deck": 16,
          "id": "CARD.CREATIVE_AI"
        },
        {
          "floor_added_to_deck": 18,
          "id": "CARD.SYNTHESIS"
        },
        {
          "floor_added_to_deck": 19,
          "id": "CARD.COOLHEADED"
        },
        {
          "floor_added_to_deck": 21,
          "id": "CARD.WHITE_NOISE"
        },
        {
          "floor_added_to_deck": 22,
          "id": "CARD.WHITE_NOISE"
        },
        {
          "floor_added_to_deck": 22,
          "id": "CARD.HOLOGRAM"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 23,
          "id": "CARD.DARKNESS"
        },
        {
          "floor_added_to_deck": 28,
          "id": "CARD.SHADOW_SHIELD"
        },
        {
          "floor_added_to_deck": 29,
          "id": "CARD.SKIM"
        },
        {
          "floor_added_to_deck": 31,
          "id": "CARD.MODDED"
        },
        {
          "floor_added_to_deck": 33,
          "id": "CARD.COOLHEADED"
        },
        {
          "floor_added_to_deck": 34,
          "id": "CARD.MAD_SCIENCE",
          "props": {
            "ints": [
              {
                "name": "TinkerTimeType",
                "value": 2
              },
              {
                "name": "TinkerTimeRider",
                "value": 4
              }
            ]
          }
        },
        {
          "floor_added_to_deck": 40,
          "id": "CARD.BOOT_SEQUENCE"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 43,
          "id": "CARD.SUBROUTINE"
        }
      ],
      "id": 76561198218717931,
      "max_potion_slot_count": 2,
      "potions": [],
      "relics": [
        {
          "floor_added_to_deck": 1,
          "id": "RELIC.CRACKED_CORE"
        },
        {
          "floor_added_to_deck": 1,
          "id": "RELIC.SCROLL_BOXES"
        },
        {
          "floor_added_to_deck": 9,
          "id": "RELIC.BAG_OF_PREPARATION"
        },
        {
          "floor_added_to_deck": 10,
          "id": "RELIC.BAG_OF_MARBLES"
        },
        {
          "floor_added_to_deck": 14,
          "id": "RELIC.STRAWBERRY"
        },
        {
          "floor_added_to_deck": 17,
          "id": "RELIC.PAELS_TEARS"
        },
        {
          "floor_added_to_deck": 20,
          "id": "RELIC.STONE_CALENDAR"
        },
        {
          "floor_added_to_deck": 23,
          "id": "RELIC.SHOVEL"
        },
        {
          "floor_added_to_deck": 24,
          "id": "RELIC.STRIKE_DUMMY"
        },
        {
          "floor_added_to_deck": 25,
          "id": "RELIC.MINIATURE_CANNON"
        },
        {
          "floor_added_to_deck": 27,
          "id": "RELIC.TUNING_FORK",
          "props": {
            "ints": [
              {
                "name": "SkillsPlayed",
                "value": 0
              }
            ]
          }
        },
        {
          "floor_added_to_deck": 28,
          "id": "RELIC.ANCHOR"
        },
        {
          "floor_added_to_deck": 30,
          "id": "RELIC.VAJRA"
        },
        {
          "floor_added_to_deck": 32,
          "id": "RELIC.CROSSBOW"
        },
        {
          "floor_added_to_deck": 36,
          "id": "RELIC.ICE_CREAM"
        },
        {
          "floor_added_to_deck": 37,
          "id": "RELIC.RAINBOW_RING"
        },
        {
          "floor_added_to_deck": 38,
          "id": "RELIC.CHANDELIER"
        },
        {
          "floor_added_to_deck": 39,
          "id": "RELIC.LANTERN"
        },
        {
          "floor_added_to_deck": 41,
          "id": "RELIC.MERCURY_HOURGLASS"
        },
        {
          "floor_added_to_deck": 42,
          "id": "RELIC.ETERNAL_FEATHER"
        },
        {
          "floor_added_to_deck": 43,
          "id": "RELIC.DATA_DISK"
        },
        {
          "floor_added_to_deck": 44,
          "id": "RELIC.WHETSTONE"
        }
      ]
    },
    {
      "badges": [
        {
          "id": "ELITE",
          "rarity": "silver"
        },
        {
          "id": "HEALER",
          "rarity": "silver"
        },
        {
          "id": "PERFECT",
          "rarity": "silver"
        },
        {
          "id": "RESTLESS",
          "rarity": "bronze"
        }
      ],
      "character": "CHARACTER.DEFECT",
      "deck": [
        {
          "floor_added_to_deck": 1,
          "id": "CARD.STRIKE_DEFECT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.STRIKE_DEFECT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.STRIKE_DEFECT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_DEFECT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_DEFECT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_DEFECT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_DEFECT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.ZAP"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DUALCAST"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.ASCENDERS_BANE"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 2,
          "id": "CARD.LOOP"
        },
        {
          "floor_added_to_deck": 3,
          "id": "CARD.FOCUSED_STRIKE"
        },
        {
          "floor_added_to_deck": 4,
          "id": "CARD.TORIC_TOUGHNESS"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 5,
          "id": "CARD.NULL"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 6,
          "id": "CARD.COMPACT"
        },
        {
          "floor_added_to_deck": 7,
          "id": "CARD.BOOST_AWAY"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 7,
          "id": "CARD.COOLHEADED"
        },
        {
          "floor_added_to_deck": 10,
          "id": "CARD.FIGHT_THROUGH"
        },
        {
          "floor_added_to_deck": 11,
          "id": "CARD.BOOST_AWAY"
        },
        {
          "floor_added_to_deck": 13,
          "id": "CARD.TURBO"
        },
        {
          "floor_added_to_deck": 14,
          "id": "CARD.ROCKET_PUNCH"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 16,
          "id": "CARD.TRASH_TO_TREASURE"
        },
        {
          "floor_added_to_deck": 18,
          "id": "CARD.BOOT_SEQUENCE"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 19,
          "id": "CARD.ROCKET_PUNCH"
        },
        {
          "floor_added_to_deck": 23,
          "id": "CARD.MACHINE_LEARNING"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 28,
          "id": "CARD.COMPILE_DRIVER"
        },
        {
          "floor_added_to_deck": 31,
          "id": "CARD.SIGNAL_BOOST"
        },
        {
          "floor_added_to_deck": 34,
          "id": "CARD.MAD_SCIENCE",
          "props": {
            "ints": [
              {
                "name": "TinkerTimeType",
                "value": 3
              },
              {
                "name": "TinkerTimeRider",
                "value": 7
              }
            ]
          }
        },
        {
          "floor_added_to_deck": 37,
          "id": "CARD.CLUMSY"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 41,
          "id": "CARD.FIGHT_THROUGH"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 42,
          "id": "CARD.DISCOVERY"
        }
      ],
      "id": 76561197999477537,
      "max_potion_slot_count": 4,
      "potions": [],
      "relics": [
        {
          "floor_added_to_deck": 1,
          "id": "RELIC.CRACKED_CORE"
        },
        {
          "floor_added_to_deck": 1,
          "id": "RELIC.LOST_COFFER"
        },
        {
          "floor_added_to_deck": 9,
          "id": "RELIC.STURDY_CLAMP"
        },
        {
          "floor_added_to_deck": 10,
          "id": "RELIC.MERCURY_HOURGLASS"
        },
        {
          "floor_added_to_deck": 14,
          "id": "RELIC.KUNAI"
        },
        {
          "floor_added_to_deck": 17,
          "id": "RELIC.PAELS_LEGION",
          "props": {
            "strings": [
              {
                "name": "Skin",
                "value": "horns"
              }
            ]
          }
        },
        {
          "floor_added_to_deck": 20,
          "id": "RELIC.POTION_BELT"
        },
        {
          "floor_added_to_deck": 22,
          "id": "RELIC.HORN_CLEAT"
        },
        {
          "floor_added_to_deck": 23,
          "id": "RELIC.SHURIKEN"
        },
        {
          "floor_added_to_deck": 24,
          "id": "RELIC.PETRIFIED_TOAD"
        },
        {
          "floor_added_to_deck": 28,
          "id": "RELIC.VAJRA"
        },
        {
          "floor_added_to_deck": 32,
          "id": "RELIC.CROSSBOW"
        },
        {
          "floor_added_to_deck": 36,
          "id": "RELIC.ORICHALCUM"
        },
        {
          "floor_added_to_deck": 37,
          "id": "RELIC.HAPPY_FLOWER",
          "props": {
            "ints": [
              {
                "name": "TurnsSeen",
                "value": 2
              }
            ]
          }
        },
        {
          "floor_added_to_deck": 38,
          "id": "RELIC.BLOOD_VIAL"
        },
        {
          "floor_added_to_deck": 41,
          "id": "RELIC.TUNGSTEN_ROD"
        },
        {
          "floor_added_to_deck": 42,
          "id": "RELIC.DATA_DISK"
        },
        {
          "floor_added_to_deck": 42,
          "id": "RELIC.ODDLY_SMOOTH_STONE"
        },
        {
          "floor_added_to_deck": 43,
          "id": "RELIC.ORNAMENTAL_FAN"
        }
      ]
    },
    {
      "badges": [
        {
          "id": "ELITE",
          "rarity": "silver"
        }
      ],
      "character": "CHARACTER.DEFECT",
      "deck": [
        {
          "floor_added_to_deck": 1,
          "id": "CARD.STRIKE_DEFECT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.STRIKE_DEFECT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_DEFECT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_DEFECT"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_DEFECT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_DEFECT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.ZAP"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DUALCAST"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.ASCENDERS_BANE"
        },
        {
          "current_upgrade_level": 1,
          "enchantment": {
            "amount": 1,
            "id": "ENCHANTMENT.SLITHER"
          },
          "floor_added_to_deck": 1,
          "id": "CARD.ECHO_FORM"
        },
        {
          "floor_added_to_deck": 2,
          "id": "CARD.UPROAR"
        },
        {
          "floor_added_to_deck": 3,
          "id": "CARD.ROCKET_PUNCH"
        },
        {
          "floor_added_to_deck": 5,
          "id": "CARD.SWEEPING_BEAM"
        },
        {
          "floor_added_to_deck": 6,
          "id": "CARD.CAPACITOR"
        },
        {
          "floor_added_to_deck": 7,
          "id": "CARD.BALL_LIGHTNING"
        },
        {
          "floor_added_to_deck": 7,
          "id": "CARD.HOLOGRAM"
        },
        {
          "floor_added_to_deck": 10,
          "id": "CARD.NULL"
        },
        {
          "floor_added_to_deck": 13,
          "id": "CARD.BULK_UP"
        },
        {
          "floor_added_to_deck": 14,
          "id": "CARD.METEOR_STRIKE"
        },
        {
          "floor_added_to_deck": 16,
          "id": "CARD.METEOR_STRIKE"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 17,
          "id": "CARD.RELAX"
        },
        {
          "floor_added_to_deck": 17,
          "id": "CARD.RELAX"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 21,
          "id": "CARD.WHITE_NOISE"
        },
        {
          "floor_added_to_deck": 22,
          "id": "CARD.ITERATION"
        },
        {
          "floor_added_to_deck": 22,
          "id": "CARD.OVERCLOCK"
        },
        {
          "floor_added_to_deck": 22,
          "id": "CARD.TURBO"
        },
        {
          "floor_added_to_deck": 28,
          "id": "CARD.FIGHT_THROUGH"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 29,
          "id": "CARD.BOOST_AWAY"
        },
        {
          "floor_added_to_deck": 31,
          "id": "CARD.DEFRAGMENT"
        },
        {
          "floor_added_to_deck": 33,
          "id": "CARD.SYNTHESIS"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 34,
          "id": "CARD.MAD_SCIENCE",
          "props": {
            "ints": [
              {
                "name": "TinkerTimeType",
                "value": 2
              },
              {
                "name": "TinkerTimeRider",
                "value": 5
              }
            ]
          }
        },
        {
          "floor_added_to_deck": 42,
          "id": "CARD.BEACON_OF_HOPE"
        },
        {
          "floor_added_to_deck": 43,
          "id": "CARD.OVERCLOCK"
        }
      ],
      "id": 76561198005465391,
      "max_potion_slot_count": 2,
      "potions": [],
      "relics": [
        {
          "floor_added_to_deck": 1,
          "id": "RELIC.CRACKED_CORE"
        },
        {
          "floor_added_to_deck": 1,
          "id": "RELIC.ARCANE_SCROLL"
        },
        {
          "floor_added_to_deck": 9,
          "id": "RELIC.PENDULUM",
          "props": {
            "ints": [
              {
                "name": "TurnsSeen",
                "value": 1
              }
            ]
          }
        },
        {
          "floor_added_to_deck": 10,
          "id": "RELIC.TUNING_FORK",
          "props": {
            "ints": [
              {
                "name": "SkillsPlayed",
                "value": 7
              }
            ]
          }
        },
        {
          "floor_added_to_deck": 14,
          "id": "RELIC.ANCHOR"
        },
        {
          "floor_added_to_deck": 17,
          "id": "RELIC.PAELS_HORN"
        },
        {
          "floor_added_to_deck": 20,
          "id": "RELIC.ODDLY_SMOOTH_STONE"
        },
        {
          "floor_added_to_deck": 23,
          "id": "RELIC.CENTENNIAL_PUZZLE"
        },
        {
          "floor_added_to_deck": 24,
          "id": "RELIC.VENERABLE_TEA_SET",
          "props": {
            "bools": [
              {
                "name": "GainEnergyInNextCombat",
                "value": false
              }
            ]
          }
        },
        {
          "floor_added_to_deck": 28,
          "id": "RELIC.PLANISPHERE"
        },
        {
          "floor_added_to_deck": 32,
          "id": "RELIC.CROSSBOW"
        },
        {
          "floor_added_to_deck": 36,
          "id": "RELIC.WAR_PAINT"
        },
        {
          "floor_added_to_deck": 38,
          "id": "RELIC.RIPPLE_BASIN"
        },
        {
          "floor_added_to_deck": 41,
          "id": "RELIC.NUNCHAKU",
          "props": {
            "ints": [
              {
                "name": "AttacksPlayed",
                "value": 79
              }
            ]
          }
        },
        {
          "floor_added_to_deck": 43,
          "id": "RELIC.RED_MASK"
        }
      ]
    }
  ],
  "run_time": 6476,
  "schema_version": 9,
  "seed": "XVBKQ6HXKS",
  "start_time": 1775515162,
  "was_abandoned": false,
  "win": true
}